################################################################################
# data_config.py
#
# These configuration parameters are specific to the data sets that are being
# imported. See also mult_config.py.
################################################################################

# param_info form types that invoke mult_ tables
GROUP_FORM_TYPES = ['GROUP', 'TARGETS']

# A list of all tables we populate, in order, for each observation index row.
# If you change something here, be sure to update do_table_names.py as well.
TABLES_TO_POPULATE = ['obs_general',
                      'obs_pds',
                      'obs_mission_<MISSION>',
                      'obs_instrument_<INST>',
                      'obs_type_image',
                      'obs_wavelength',
                      'obs_profile',
                      'obs_files',
                      'obs_ring_geometry',
                      'obs_surface_geometry',
                      'obs_surface_geometry_name',
                      'obs_surface_geometry__<TARGET>']

# These mult tables have an extra column to allow for target_name grouping
MULT_TABLES_WITH_TARGET_GROUPING = ['mult_obs_general_target_name',
                                   'mult_obs_surface_geometry_name_target_name']

# These instruments have ring geo available (maybe)
# This is only used to give a warning if the ring geo isn't available
VOLSETS_WITH_RING_GEO = ['COISS_1xxx',
                         'COISS_2xxx',
                         'COUVIS_0xxx',
                         'COVIMS_0xxx',
                         'NHxxLO_xxxx',
                         'VGISS_5xxx',
                         'VGISS_6xxx',
                         'VGISS_7xxx',
                         'VGISS_8xxx']

# These instruments have surface geo available (maybe)
# This is only used to give a warning if the surface geo isn't available
VOLSETS_WITH_SURFACE_GEO = ['COCIRS_0xxx_CUBE_EQUI',
                            'COCIRS_1xxx_CUBE_EQUI',
                            'COISS_1xxx',
                            'COISS_2xxx',
                            'COUVIS_0xxx',
                            'COVIMS_0xxx',
                            'NHxxLO_xxxx',
                            'VGISS_5xxx',
                            'VGISS_6xxx',
                            'VGISS_7xxx',
                            'VGISS_8xxx']

# Also modify populate_obs_general_preview_images as necessary
VOLSETS_WITH_PREVIEWS = ['COISS_1xxx',
                         'COISS_2xxx',
                         'COCIRS_5xxx',
                         'COCIRS_6xxx',
                         'COUVIS_0xxx',
                         'COUVIS_8xxx',
                         'COVIMS_0xxx',
                         'COVIMS_8xxx',
                         'EBROCC_0xxx',
                         'GO_0xxx',
                         'HSTIx_xxxx',
                         'HSTJx_xxxx',
                         'HSTNx_xxxx',
                         'HSTOx_xxxx',
                         'HSTUx_xxxx',
                         'NHxxLO_xxxx',
                         'NHxxMV_xxxx',
                         'VGISS_5xxx',
                         'VGISS_6xxx',
                         'VGISS_7xxx',
                         'VGISS_8xxx']

# Mapping from mission abbreviation (UC) to full mission name (LC)
# These are used for table names
MISSION_ABBREV_TO_MISSION_TABLE_SFX = {
    'CO':  'cassini',
    'GB':  'earth',
    'GO':  'galileo',
    'HST': 'hubble',
    'NH':  'new_horizons',
    'VG':  'voyager'
}

# Mapping from mission abbreviation (UC) to full mission name (displayable)
MISSION_ABBREV_TO_MISSION_NAME = {
    'CO':  'Cassini',
    'GB':  'Ground-based',
    'GO':  'Galileo',
    'HST': 'Hubble',
    'NH':  'New Horizons',
    'VG':  'Voyager'
}

# Mapping from instrument host abbreviation to mission abbreviation
INST_HOST_ABBREV_TO_MISSION_ABBREV = {
    'CO':  'CO',
    'GB':  'GB',
    'GO':  'GO',
    'HST': 'HST',
    'NH':  'NH',
    'VG1': 'VG',
    'VG2': 'VG'
}

# Mapping from instrument host abbreviation to instrument host name
INST_HOST_ABBREV_TO_INST_HOST = {
    'CO':  'Cassini',
    'GB':  'Ground-based',
    'GO':  'Galileo',
    'HST': 'Hubble',
    'NH':  'New Horizons',
    'VG1': 'Voyager 1',
    'VG2': 'Voyager 2'
}

# Mapping from instrument abbreviation to mission abbreviation
INSTRUMENT_ABBREV_TO_MISSION_ABBREV = {
    'COCIRS':    'CO',
    'COISS':     'CO',
    'CORSS':     'CO',
    'COUVIS':    'CO',
    'COVIMS':    'CO',
    'GOSSI':     'GO',
    'HSTACS':    'HST',
    'HSTNICMOS': 'HST',
    'HSTSTIS':   'HST',
    'HSTWFC3':   'HST',
    'HSTWFPC2':  'HST',
    'NHLORRI':   'NH',
    'NHMVIC':    'NH',
    'VGISS':     'VG',
    'VGPPS':     'VG',
    'VGRSS':     'VG',
    'VGUVS':     'VG',
}

# Mapping from instrument abbrev to instrument name
INSTRUMENT_ABBREV_TO_INSTRUMENT_NAME = {
    'COCIRS':      'Cassini CIRS',
    'COISS':       'Cassini ISS',
    'COUVIS':      'Cassini UVIS',
    'COVIMS':      'Cassini VIMS',
    'GOSSI':       'Galileo SSI',
    'HSTACS':      'Hubble ACS',
    'HSTNICMOS':   'Hubble NICMOS',
    'HSTSTIS':     'Hubble STIS',
    'HSTWFC3':     'Hubble WFC3',
    'HSTWFPC2':    'Hubble WFPC2',
    'NHLORRI':     'New Horizons LORRI',
    'NHMVIC':      'New Horizons MVIC',
    'VGISS':       'Voyager ISS',
    'VGPPS':       'Voyager PPS',
    'VGRSS':       'Voyager RSS',
    'VGUVS':       'Voyager UVS',
    # Ground-based
    'ESO1MAPPH':   'ESO 1-Meter Aperture Photometer',
    'ESO22MAPPH':  'ESO 2.2-Meter Aperture Photometer',
    'IRTFURAC':    'NASA IRTF URAC',
    'LICK1MCCDC':  'Lick 1-Meter CCD Camera',
    'MCD27MIIRAR': 'McDonald Observatory 2.7-Meter INSB IR Array',
    'PAL200CIRC':  'Palomar Observatory 200-Inch Cassegrain IR Camera'
}

# Mapping from VOLUME ID prefix to instrument name
VOLUME_ID_PREFIX_TO_INSTRUMENT_NAME = {
    'COCIRS': 'COCIRS',
    'COISS':  'COISS',
    'CORSS':  'CORSS',
    'COUVIS': 'COUVIS',
    'COVIMS': 'COVIMS',
    'EBROCC': None, # The instrument must be looked up in the label file
    'GO':     'GOSSI',
    'HSTI1':  'HSTWFC3',
    'HSTJ0':  'HSTACS',
    'HSTJ1':  'HSTACS',
    'HSTN0':  'HSTNICMOS',
    'HSTN1':  'HSTNICMOS',
    'HSTO0':  'HSTSTIS',
    'HSTO1':  'HSTSTIS',
    'HSTU0':  'HSTWFPC2',
    'HSTU1':  'HSTWFPC2',
    'NHJULO': 'NHLORRI',
    'NHLALO': 'NHLORRI',
    'NHPCLO': 'NHLORRI',
    'NHPELO': 'NHLORRI',
    'NHJUMV': 'NHMVIC',
    'NHLAMV': 'NHMVIC',
    'NHPCMV': 'NHMVIC',
    'NHPEMV': 'NHMVIC',
    'VGISS':  'VGISS',
    'VG':     {
        'VG_2801': 'VGPPS',
        'VG_2802': 'VGUVS',
        'VG_2803': 'VGRSS',
        'VG_2810': 'VGISS',
    }
}

# Mapping from VOLUME ID prefix to mission abbreviation
VOLUME_ID_PREFIX_TO_MISSION_ABBREV = {
    'COCIRS': 'CO',
    'COISS':  'CO',
    'CORSS':  'CO',
    'COUVIS': 'CO',
    'COVIMS': 'CO',
    'EBROCC': 'GB',
    'GO':     'GO',
    'HSTI1':  'HST',
    'HSTJ0':  'HST',
    'HSTJ1':  'HST',
    'HSTN0':  'HST',
    'HSTN1':  'HST',
    'HSTO0':  'HST',
    'HSTO1':  'HST',
    'HSTU0':  'HST',
    'HSTU1':  'HST',
    'NHJULO': 'NH',
    'NHLALO': 'NH',
    'NHPCLO': 'NH',
    'NHPELO': 'NH',
    'NHJUMV': 'NH',
    'NHLAMV': 'NH',
    'NHPCMV': 'NH',
    'NHPEMV': 'NH',
    'VGISS':  'VG',
    'VG':     'VG',
}

# Mapping from VOLUME root to observation type
VOLUME_ID_ROOT_TO_TYPE = {
    'COCIRS_0xxx': 'CUBE',
    'COCIRS_1xxx': 'CUBE',
    'COCIRS_5xxx': 'OBS',
    'COCIRS_6xxx': 'OBS',
    'COISS_1xxx':  'OBS',
    'COISS_2xxx':  'OBS',
    'CORSS_8xxx':  'PROF',
    'COUVIS_0xxx': 'OBS',
    'COUVIS_8xxx': 'PROF',
    'COVIMS_0xxx': 'OBS',
    'COVIMS_8xxx': 'PROF',
    'EBROCC_xxxx': 'PROF',
    'GO_0xxx':     'OBS',
    'HSTIx_xxxx':  'OBS',
    'HSTJx_xxxx':  'OBS',
    'HSTNx_xxxx':  'OBS',
    'HSTOx_xxxx':  'OBS',
    'HSTUx_xxxx':  'OBS',
    'NHxxLO_xxxx': 'OBS',
    'NHxxMV_xxxx': 'OBS',
    'VG_28xx':     'PROF',
    'VGISS_5xxx':  'OBS',
    'VGISS_6xxx':  'OBS',
    'VGISS_7xxx':  'OBS',
    'VGISS_8xxx':  'OBS'
}

# Some instruments (I'm looking at you, Cassini) don't use the official IAU
# names for targets, but we want to in OPUS.
TARGET_NAME_MAPPING = {
    # This is found in COCIRS_0xxx/1xxx
    'S_RINGS':          'S RINGS',
    # These are found in COISS
    'ERRIAPO':          'ERRIAPUS',
    'HYROKKIN':         'HYRROKKIN',
    'K07S4':            'ANTHE',
    'SKADI':            'SKATHI',
    'SUTTUNG':          'SUTTUNGR',
    'THRYM':            'THRYMR',

    'S7_2004':          'S/2004 S 7',
    'S8_2004':          'FORNJOT',
    'S12_2004':         'S/2004 S 12',
    'S13_2004':         'S/2004 S 13',
    'S14_2004':         'HATI',
    'S17_2004':         'S/2004 S 17',
    'S18_2004':         'BESTLA',
    'S1_2006':          'S/2006 S 1',
    'S3_2006':          'S/2006 S 3',
    'S2_2007':          'S/2007 S 2',
    'S3_2007':          'S/2007 S 3',

    # These are found in COUVIS
    'ATLAS:':           'ATLAS',
    'AG':               'AEGAEON',
    'DA':               'DAPHNIS',
    'ME':               'METHONE',
    'PL':               'PALLENE',
    'PO':               'POLYDEUCES',
    'IPH':              'INTERSTELLAR MEDIUM', # Interstellar H/He survey

    # These are found in HST
    '174567-VARDA':     'VARDA',
    '90482ORCUS':       'ORCUS',
    '1999HG12':         '1999 HG12',
    '118378':           '1999 HT11',
    '1999-RT214':       '1999 RT214',
    '80806':            '2000 CM105',
    '60458-2000-CM114': '2000 CM114',
    '2000CQ114':        '2000 CQ114',
    '2000-CQ114':       '2000 CQ114',
    '2000-FC8':         '2000 FC8',
    '2000-OB51':        '2000 OB51',
    '2000-PM30':        '2000 PM30',
    '2000-PN30':        '2000 PN30',
    '2000QN251':        '2000 QN251',
    '2001-FL185':       '2001 FL185',
    '119070':           '2001 KP77',
    '2002VV130':        '2002 VV130',
    '119979':           '2002 WC19',
    '182933':           '2002 GZ31',
    '2002UX25':         '2002 UX25',
    '2003TJ58':         '2003 TJ58',
    '2003QW111':        'MANWE',
    '2003UB313':        'ERIS',
    '2004VE131':        '2004 VE131',
    '2005EF298':        '2005 EF298',
    '2005SE278':        '2005 SE278',
    '2005SF278':        '2005 SF278',
    '2011-JX31':        '2011 JX31',
    '2014MU69':         '2014 MU69',
    '2014PN70':         '2014 PN70',
    'KBO-G1':           '2014 PN70',
    'NECKLACE-NEBULA':  'NECKLACE NEBULA',
    'CHARIKLORING':     'CHARIKLO RING',

    # These are found in NH
    '136472 MAKEMAKE':  'MAKEMAKE',
    '136108 HAUMEA':    'HAUMEA',
    '10199 CHARIKLO':   'CHARIKLO',
    '15810 ARAWN':      'ARAWN',
    '50000 QUAOAR':     'QUAOAR',
    '28978 IXION':      'IXION',
    'ASTEROID 307261':  '2002 MS4',
    '2060 CHIRON':      'CHIRON',
    '132524 APL':       '2002 JF56',

    # Misc
    'S/2000 J 11':      'DIA',

    'CALIB':            'CALIBRATION',
    'N/A':              'NONE',
    'UNK':              'UNKNOWN',
    'UNK SAT':          'UNKNOWN',
    'NON_SCIENC':       'NONE',
    'NON SCIENC':       'NONE',
    'NON SCIENCE':      'NONE',

    # Stars
    '126 TAU':          '126_TAU',
    '126TAU':           '126_TAU',
    '205839':           'B_CEN',
    '26TAU':            '26_TAU',
    '2CEN':             'G_CEN',
    '28SGR':            '28_SGR',
    '28 SGR':           '28_SGR',
    '30HER':            'G_HER',
    '30PSC':            '30_PSC',
    '3CEN':             '3_CEN',
    '56LEO':            '56_LEO',
    '78TAU':            'TET02_TAU',
    'ALP1CRU':          'ALF01_CRU',
    'ALPARA':           'ALF_ARA',
    'ALPAUR':           'ALF_AUR',
    'ALPCEN':           'ALF_CEN',
    'ALPCET':           'ALF_CET',
    'ALPCMA':           'ALF_CMA',
    'ALPCMI':           'ALF_CMI',
    'ALPCRU':           'ALF_CRU',
    'ALPERI':           'ALF_ERI',
    'ALPHER':           'ALF_HER',
    'ALPHYA':           'ALF_HYA',
    'ALPLEO':           'ALF_LEO',
    'ALPLUP':           'ALF_LUP',
    'ALPLYR':           'ALF_LYR',
    'ALPORI':           'ALF_ORI',
    'ALPPAV':           'ALF_PAV',
    'ALPSCO':           'ALF_SCO',
    'ALPSEX':           'ALF_SEX',
    'ALPTAU':           'ALF_TAU',
    'ALPTRA':           'ALF_TRA',
    'ALPVIR':           'ALF_VIR',
    'ARCTURUS':         'ALF_BOO',
    'BETAND':           'BET_AND',
    'BETCEN':           'BET_CEN',
    'BETCMA':           'BET_CMA',
    'BETA CMA':         'BET_CMA',
    'BETCRU':           'BET_CRU',
    'BETGRU':           'BET_GRU',
    'BETHYA':           'BET_HYA',
    'BETLIB':           'BET_LIB',
    'BETLUP':           'BET_LUP',
    'BETORI':           'BET_ORI',
    'BETPEG':           'BET_PEG',
    'BETPER':           'BET_PER',
    'BETA PER':         'BET_PER',
    'BETPSA':           'BET_PSA',
    'BETSGR':           'BET01_SGR',
    'BETUMI':           'BET_UMI',
    'CALSTAR3':         'KAP01_CET',
    'CANOPUS':          'ALF_CAR',
    'CHIAQR':           'CHI_AQR',
    'CHICEN':           'CHI_CEN',
    'CHICYG':           'CHI_CYG',
    'CWLEO':            'IRC_+10216',
    'DELAQR':           'DEL_AQR',
    'DELCEN':           'DEL_CEN',
    'DELCET':           'DEL_CET',
    'DELLUP':           'DEL_LUP',
    'DELOPH':           'DEL_OPH',
    'DELORI':           'DEL_ORI',
    'DELPER':           'DEL_PER',
    'DELSCO':           'DEL_SCO',
    'DELTA SCO':        'DEL_SCO',
    'DELVIR':           'DEL_VIR',
    'EPSCAS':           'EPS_CAS',
    'EPSCEN':           'EPS_CEN',
    'EPSCMA':           'EPS_CMA',
    'EPSLUP':           'EPS_LUP',
    'EPSMIC':           'EPS_MIC',
    'EPSMUS':           'EPS_MUS',
    'EPSORI':           'EPS_ORI',
    'EPSPEG':           'EPS_PEG',
    'EPSPER':           'EPS_PER',
    'EPSPSA':           'EPS_PSA',
    'EPSSGR':           'EPS_SGR',
    'ETACAR':           'ETA_CAR',
    'ETACMA':           'ETA_CMA',
    'ETALUP':           'ETA_LUP',
    'ETASGR':           'ETA_SGR',
    'ETAUMA':           'ETA_UMA',
    'FOMALHAUT':        'ALF_PSA',
    'GAMAND':           'GAM_AND',
    'GAMARA':           'GAM_ARA',
    'GAMCAS':           'GAM_CAS',
    'GAMCNC':           'GAM_CNC',
    'GAMCOL':           'GAM_COL',
    'GAMCRU':           'GAM_CRU',
    'GAMERI':           'GAM_ERI',
    'GAMGRU':           'GAM_GRU',
    'GAMLUP':           'GAM_LUP',
    'GAMORI':           'GAM_ORI',
    'GAMPEG':           'GAM_PEG',
    'HD 205905':        'HD_205905',
    'HD339':            'HD_339479',
    'HD 37962':         'HD_37962',
    'HD71334':          'HD_71334',
    'IOTHER':           'IO_HER',
    'IOTA HER':         'IO_HER',
    'IOTCEN':           'IO_CEN',
    'IOTORI':           'IO_ORI',
    'KAPCEN':           'KAP_CEN',
    'KAPCMA':           'KAP_CMA',
    'KAPORI':           'KAP_ORI',
    'KAPSCO':           'KAP_SCO',
    'KAPVEL':           'KAP_VEL',
    'L2PUP':            'L2_PUP',
    'LAMAQL':           'LAM_AQL',
    'LAMAQR':           'LAM_AQR',
    'LAMCET':           'LAM_CET',
    'LAMSCO':           'LAM_SCO',
    'LAMTAU':           'LAM_TAU',
    'LAMVEL':           'LAM_VEL',
    'LMC303':           'LMC_303',
    'MUCEN':            'MU_CEN',
    'MUCEP':            'MU_CEP',
    'MUGEM':            'MU_GEM',
    'MUPSA':            'MU_PSA',
    'MUSCO':            'MU_SCO',
    'MUSGR':            'MU_SGR',
    'NMLTAURI':         'IK_TAU',
    'NUCEN':            'NU_CEN',
    'NUVIR':            'NU_VIR',
    'OMEVIR':           'OME_VIR',
    'OMICET':           'OMI_CET',
    'PI1GRU':           'PI.01_GRU',
    'PI4ORI':           'PI.04_ORI',
    'PSICEN':           'PSI_CEN',
    'RAQL':             'R_AQL',
    'RAQR':             'R_AQR',
    'RCAR':             'R_CAR',
    'RCAS':             'R_CAS',
    'RDOR':             'R_DOR',
    'RDORADUS':         'R_DOR',
    'RHOPER':           'RHO_PER',
    'RHYA':             'R_HYA',
    'RLEO':             'R_LEO',
    'RLYR':             '13_LYR',
    'RSCNC':            'RS_CNC',
    'RWLMI':            'RW_LMI',
    'RXLEP':            'RX_LEP',
    'SAO205839':        'B_CEN',
    'SIGSGR':           'SIG_SGR',
    'SIGMA SGR':        'SIG_SGR',
    'SLEP':             'S_LEP',
    'SPICA':            'ALF_VIR',
    'TAU78':            'TET02_TAU',
    'TCEP':             'T_CEP',
    'THEARA':           'TET_ARA',
    'THECAR':           'TET_CAR',
    'THETA CAR':        'TET_CAR',
    'THEHYA':           'TET_HYA',
    'TXCAM':            'TX_CAM',
    'VEGA':             'ALF_LYR',
    'VHYA':             'V_HYA',
    'VXSGR':            'VX_SGR',
    'VYCMA':            'VY_CMA',
    'WAQL':             'W_AQL',
    'WHYA':             'W_HYA',
    'XI1CET':           'KSI01_CET',
    'XI2CET':           'KSI02_CET',
    'XOPH':             'X_OPH',
    'ZETCEN':           'ZET_CEN',
    'ZETCMA':           'ZET_CMA',
    'ZETOPH':           'ZET_OPH',
    'ZETORI':           'ZET_ORI',
    'ZETPER':           'ZET_PER',
    'ZETPUP':           'ZET_PUP',
}

# Map each possible target name to:
#   1. Planet name it is associated with, or None if not associated with a
#      planet
#   2. Target class
#   3. Pretty name
# Note that if you add a new target class here, you also have to update the
# enum field and mult_options in obs_general.json
TARGET_NAME_INFO = {
    'NONE':                 (None,  'OTHER',        'None'),
    'UNKNOWN':              (None,  'OTHER',        'Unknown'),
    'OTHER':                (None,  'OTHER',        'Other'),
    'DARK':                 (None,  'CALIBRATION',  'Dark'),
    'CALIBRATION':          (None,  'CALIBRATION',  'Calibration'),
    'CAL LAMPS':            (None,  'CALIBRATION',  'Calibration Lamps'),
    'PLAQUE':               (None,  'CALIBRATION',  'Plaque'),
    'SKY':                  (None,  'SKY',          'Sky'),
    'BLACK SKY':            (None,  'SKY',          'Black Sky'),
    'DARK SKY':             (None,  'SKY',          'Dark Sky'),
    'SOLAR WIND':           (None,  'OTHER',        'Solar Wind'),
    'INTERSTELLAR MEDIUM':  (None,  'OTHER',        'Interstellar Medium'),
    'DUST':                 (None,  'OTHER',        'Dust'),

    'VENUS':                ('VEN', 'PLANET',       'Venus'),

    'EARTH':                ('EAR', 'PLANET',       'Earth'),
      'MOON':               ('EAR', 'REG_SAT',      'Moon'), # noqa: E131

    'MARS':                 ('MAR', 'PLANET',       'Mars'),

    'JUPITER':              ('JUP', 'PLANET',       'Jupiter'),
      'ADRASTEA':           ('JUP', 'REG_SAT',      'Adrastea'),
      'AITNE':              ('JUP', 'IRR_SAT',      'Aitne'),
      'AMALTHEA':           ('JUP', 'REG_SAT',      'Amalthea'),
      'ANANKE':             ('JUP', 'IRR_SAT',      'Ananke'),
      'AOEDE':              ('JUP', 'IRR_SAT',      'Aoede'),
      'ARCHE':              ('JUP', 'IRR_SAT',      'Arche'),
      'AUTONOE':            ('JUP', 'IRR_SAT',      'Autonoe'),
      'CALLIRRHOE':         ('JUP', 'IRR_SAT',      'Callirrhoe'),
      'CALLISTO':           ('JUP', 'REG_SAT',      'Callisto'),
      'CARME':              ('JUP', 'IRR_SAT',      'Carme'),
      'CARPO':              ('JUP', 'IRR_SAT',      'Carpo'),
      'CHALDENE':           ('JUP', 'IRR_SAT',      'Chaldene'),
      'CYLLENE':            ('JUP', 'IRR_SAT',      'Cyllene'),
      'DIA':                ('JUP', 'IRR_SAT',      'Dia'),
      'ELARA':              ('JUP', 'IRR_SAT',      'Elara'),
      'ERINOME':            ('JUP', 'IRR_SAT',      'Erinome'),
      'EUANTHE':            ('JUP', 'IRR_SAT',      'Euanthe'),
      'EUKELADE':           ('JUP', 'IRR_SAT',      'Eukelade'),
      'EUPORIE':            ('JUP', 'IRR_SAT',      'Euporie'),
      'EUROPA':             ('JUP', 'REG_SAT',      'Europa'),
      'EURYDOME':           ('JUP', 'IRR_SAT',      'Eurydome'),
      'GANYMEDE':           ('JUP', 'REG_SAT',      'Ganymede'),
      'HARPALYKE':          ('JUP', 'IRR_SAT',      'Harpalyke'),
      'HEGEMONE':           ('JUP', 'IRR_SAT',      'Hegemone'),
      'HELIKE':             ('JUP', 'IRR_SAT',      'Helike'),
      'HERMIPPE':           ('JUP', 'IRR_SAT',      'Hermippe'),
      'HERSE':              ('JUP', 'IRR_SAT',      'Herse'),
      'HIMALIA':            ('JUP', 'IRR_SAT',      'Himalia'),
      'IO':                 ('JUP', 'REG_SAT',      'Io'),
      'IOCASTE':            ('JUP', 'IRR_SAT',      'Iocaste'),
      'ISONOE':             ('JUP', 'IRR_SAT',      'Isonoe'),
      'KALE':               ('JUP', 'IRR_SAT',      'Kale'),
      'KALLICHOR':          ('JUP', 'IRR_SAT',      'Kallichor'),
      'KALYKE':             ('JUP', 'IRR_SAT',      'Kalyke'),
      'KORE':               ('JUP', 'IRR_SAT',      'Kore'),
      'LEDA':               ('JUP', 'IRR_SAT',      'Leda'),
      'LYSITHEA':           ('JUP', 'IRR_SAT',      'Lysithea'),
      'MEGACLITE':          ('JUP', 'IRR_SAT',      'Megaclite'),
      'METIS':              ('JUP', 'REG_SAT',      'Metis'),
      'MNEME':              ('JUP', 'IRR_SAT',      'Mneme'),
      'ORTHOSIE':           ('JUP', 'IRR_SAT',      'Orthosie'),
      'PASIPHAE':           ('JUP', 'IRR_SAT',      'Pasiphae'),
      'PASITHEE':           ('JUP', 'IRR_SAT',      'Pasithee'),
      'PRAXIDIKE':          ('JUP', 'IRR_SAT',      'Praxidike'),
      'S/2003 J 2':         ('JUP', 'IRR_SAT',      'S/2003 J 2'),
      'S/2003 J 3':         ('JUP', 'IRR_SAT',      'S/2003 J 3'),
      'S/2003 J 4':         ('JUP', 'IRR_SAT',      'S/2003 J 4'),
      'S/2003 J 5':         ('JUP', 'IRR_SAT',      'S/2003 J 5'),
      'S/2003 J 9':         ('JUP', 'IRR_SAT',      'S/2003 J 9'),
      'S/2003 J 10':        ('JUP', 'IRR_SAT',      'S/2003 J 10'),
      'S/2003 J 12':        ('JUP', 'IRR_SAT',      'S/2003 J 12'),
      'S/2003 J 15':        ('JUP', 'IRR_SAT',      'S/2003 J 15'),
      'S/2003 J 16':        ('JUP', 'IRR_SAT',      'S/2003 J 16'),
      'S/2003 J 18':        ('JUP', 'IRR_SAT',      'S/2003 J 18'),
      'S/2003 J 19':        ('JUP', 'IRR_SAT',      'S/2003 J 19'),
      'S/2003 J 23':        ('JUP', 'IRR_SAT',      'S/2003 J 23'),
      'S/2010 J 1':         ('JUP', 'IRR_SAT',      'S/2010 J 1'),
      'S/2010 J 2':         ('JUP', 'IRR_SAT',      'S/2010 J 2'),
      'S/2011 J 1':         ('JUP', 'IRR_SAT',      'S/2011 J 1'),
      'S/2011 J 2':         ('JUP', 'IRR_SAT',      'S/2011 J 2'),
      'SINOPE':             ('JUP', 'IRR_SAT',      'Sinope'),
      'SPONDE':             ('JUP', 'IRR_SAT',      'Sponde'),
      'TAYGETE':            ('JUP', 'IRR_SAT',      'Taygete'),
      'THEBE':              ('JUP', 'REG_SAT',      'Thebe'),
      'THELXINOE':          ('JUP', 'IRR_SAT',      'Thelxinoe'),
      'THEMISTO':           ('JUP', 'IRR_SAT',      'Themisto'),
      'THYONE':             ('JUP', 'IRR_SAT',      'Thyone'),
      'J MINOR SAT':        ('JUP', 'IRR_SAT',      'Jupiter Minor Satellites'),
      'J RINGS':            ('JUP', 'RING',         'Jupiter Rings'),

    'SATURN':               ('SAT', 'PLANET',       'Saturn'),
      'AEGAEON':            ('SAT', 'REG_SAT',      'Aegaeon'),
      'AEGIR':              ('SAT', 'IRR_SAT',      'Aegir'),
      'ALBIORIX':           ('SAT', 'IRR_SAT',      'Albiorix'),
      'ANTHE':              ('SAT', 'REG_SAT',      'Anthe'),
      'ATLAS':              ('SAT', 'REG_SAT',      'Atlas'),
      'BEBHIONN':           ('SAT', 'IRR_SAT',      'Bebhionn'),
      'BERGELMIR':          ('SAT', 'IRR_SAT',      'Bergelmir'),
      'BESTLA':             ('SAT', 'IRR_SAT',      'Bestla'),
      'CALYPSO':            ('SAT', 'REG_SAT',      'Calypso'),
      'DAPHNIS':            ('SAT', 'REG_SAT',      'Daphnis'),
      'DIONE':              ('SAT', 'REG_SAT',      'Dione'),
      'ENCELADUS':          ('SAT', 'REG_SAT',      'Enceladus'),
      'EPIMETHEUS':         ('SAT', 'REG_SAT',      'Epimetheus'),
      'ERRIAPUS':           ('SAT', 'IRR_SAT',      'Erriapus'),
      'FARBAUTI':           ('SAT', 'IRR_SAT',      'Farbauti'),
      'FENRIR':             ('SAT', 'IRR_SAT',      'Fenrir'),
      'FORNJOT':            ('SAT', 'IRR_SAT',      'Fornjot'),
      'GREIP':              ('SAT', 'IRR_SAT',      'Greip'),
      'HATI':               ('SAT', 'IRR_SAT',      'Hati'),
      'HELENE':             ('SAT', 'REG_SAT',      'Helene'),
      'HYPERION':           ('SAT', 'REG_SAT',      'Hyperion'),
      'HYRROKKIN':          ('SAT', 'IRR_SAT',      'Hyrrokkin'),
      'IAPETUS':            ('SAT', 'REG_SAT',      'Iapetus'),
      'IJIRAQ':             ('SAT', 'IRR_SAT',      'Ijiraq'),
      'JANUS':              ('SAT', 'REG_SAT',      'Janus'),
      'JARNSAXA':           ('SAT', 'IRR_SAT',      'Jarnsaxa'),
      'K07S4':              ('SAT', 'IRR_SAT',      'K07s4'),
      'KARI':               ('SAT', 'IRR_SAT',      'Kari'),
      'KIVIUQ':             ('SAT', 'IRR_SAT',      'Kiviuq'),
      'LOGE':               ('SAT', 'IRR_SAT',      'Loge'),
      'METHONE':            ('SAT', 'REG_SAT',      'Methone'),
      'MIMAS':              ('SAT', 'REG_SAT',      'Mimas'),
      'MUNDILFARI':         ('SAT', 'IRR_SAT',      'Mundilfari'),
      'NARVI':              ('SAT', 'IRR_SAT',      'Narvi'),
      'PAALIAQ':            ('SAT', 'IRR_SAT',      'Paaliaq'),
      'PALLENE':            ('SAT', 'REG_SAT',      'Pallene'),
      'PANDORA':            ('SAT', 'REG_SAT',      'Pandora'),
      'PAN':                ('SAT', 'REG_SAT',      'Pan'),
      'PHOEBE':             ('SAT', 'IRR_SAT',      'Phoebe'),
      'POLYDEUCES':         ('SAT', 'REG_SAT',      'Polydeuces'),
      'PROMETHEUS':         ('SAT', 'REG_SAT',      'Prometheus'),
      'RHEA':               ('SAT', 'REG_SAT',      'Rhea'),
      'S/2004 S 12':        ('SAT', 'IRR_SAT',      'S/2004 S 12'),
      'S/2004 S 13':        ('SAT', 'IRR_SAT',      'S/2004 S 13'),
      'S/2004 S 17':        ('SAT', 'IRR_SAT',      'S/2004 S 17'),
      'S/2004 S 7':         ('SAT', 'IRR_SAT',      'S/2004 S 7'),
      'S/2006 S 1':         ('SAT', 'IRR_SAT',      'S/2006 S 1'),
      'S/2006 S 3':         ('SAT', 'IRR_SAT',      'S/2006 S 3'),
      'S/2007 S 2':         ('SAT', 'IRR_SAT',      'S/2007 S 2'),
      'S/2007 S 3':         ('SAT', 'IRR_SAT',      'S/2007 S 3'),
      'SIARNAQ':            ('SAT', 'IRR_SAT',      'Siarnaq'),
      'SKATHI':             ('SAT', 'IRR_SAT',      'Skathi'),
      'SKOLL':              ('SAT', 'IRR_SAT',      'Skoll'),
      'SURTUR':             ('SAT', 'IRR_SAT',      'Surtur'),
      'SUTTUNGR':           ('SAT', 'IRR_SAT',      'Suttungr'),
      'TARQEQ':             ('SAT', 'IRR_SAT',      'Tarqeq'),
      'TARVOS':             ('SAT', 'IRR_SAT',      'Tarvos'),
      'TELESTO':            ('SAT', 'REG_SAT',      'Telesto'),
      'TETHYS':             ('SAT', 'REG_SAT',      'Tethys'),
      'THRYMR':             ('SAT', 'IRR_SAT',      'Thrymr'),
      'TITAN':              ('SAT', 'REG_SAT',      'Titan'),
      'YMIR':               ('SAT', 'IRR_SAT',      'Ymir'),
      'S RINGS':            ('SAT', 'RING',         'Saturn Rings'),

    'URANUS':               ('URA', 'PLANET',       'Uranus'),
      'ARIEL':              ('URA', 'REG_SAT',      'Ariel'),
      'BELINDA':            ('URA', 'REG_SAT',      'Belinda'),
      'BIANCA':             ('URA', 'REG_SAT',      'Bianca'),
      'CALIBAN':            ('URA', 'IRR_SAT',      'Caliban'),
      'CORDELIA':           ('URA', 'REG_SAT',      'Cordelia'),
      'CRESSIDA':           ('URA', 'REG_SAT',      'Cressida'),
      'CUPID':              ('URA', 'REG_SAT',      'Cupid'),
      'DESDEMONA':          ('URA', 'REG_SAT',      'Desdemona'),
      'FERDINAND':          ('URA', 'IRR_SAT',      'Ferdinand'),
      'FRANCISCO':          ('URA', 'IRR_SAT',      'Francisco'),
      'JULIET':             ('URA', 'REG_SAT',      'Juliet'),
      'MAB':                ('URA', 'REG_SAT',      'Mab'),
      'MARGARET':           ('URA', 'IRR_SAT',      'Margaret'),
      'MIRANDA':            ('URA', 'REG_SAT',      'Miranda'),
      'OBERON':             ('URA', 'REG_SAT',      'Oberon'),
      'OPHELIA':            ('URA', 'REG_SAT',      'Ophelia'),
      'PERDITA':            ('URA', 'REG_SAT',      'Perdita'),
      'PORTIA':             ('URA', 'REG_SAT',      'Portia'),
      'PROSPERO':           ('URA', 'IRR_SAT',      'Prospero'),
      'PUCK':               ('URA', 'REG_SAT',      'Puck'),
      'ROSALIND':           ('URA', 'REG_SAT',      'Rosalind'),
      'SETEBOS':            ('URA', 'IRR_SAT',      'Setebos'),
      'STEPHANO':           ('URA', 'IRR_SAT',      'Stephano'),
      'SYCORAX':            ('URA', 'IRR_SAT',      'Sycorax'),
      'TITANIA':            ('URA', 'REG_SAT',      'Titania'),
      'TRINCULO':           ('URA', 'IRR_SAT',      'Trinculo'),
      'UMBRIEL':            ('URA', 'REG_SAT',      'Umbriel'),
      'U RINGS':            ('URA', 'RING',         'Uranus Rings'),

    'NEPTUNE':              ('NEP', 'PLANET',       'Neptune'),
      'DESPINA':            ('NEP', 'REG_SAT',      'Despina'),
      'GALATEA':            ('NEP', 'REG_SAT',      'Galatea'),
      'HALIMEDE':           ('NEP', 'IRR_SAT',      'Halimede'),
      'LAOMEDEIA':          ('NEP', 'IRR_SAT',      'Laomedeia'),
      'LARISSA':            ('NEP', 'REG_SAT',      'Larissa'),
      'NAIAD':              ('NEP', 'REG_SAT',      'Naiad'),
      'NEREID':             ('NEP', 'IRR_SAT',      'Nereid'),
      'NESO':               ('NEP', 'IRR_SAT',      'Neso'),
      'PROTEUS':            ('NEP', 'REG_SAT',      'Proteus'),
      'PSAMATHE':           ('NEP', 'IRR_SAT',      'Psamathe'),
      'SAO':                ('NEP', 'IRR_SAT',      'Sao'),
      'THALASSA':           ('NEP', 'REG_SAT',      'Thalassa'),
      'TRITON':             ('NEP', 'IRR_SAT',      'Triton'),
      'N RINGS':            ('NEP', 'RING',         'Neptune Rings'),

    'PLUTO':                ('PLU', 'PLANET',       'Pluto'),
      'CHARON':             ('PLU', 'REG_SAT',      'Charon'),
      'HYDRA':              ('PLU', 'REG_SAT',      'Hydra'),
      'KERBEROS':           ('PLU', 'REG_SAT',      'Kerberos'),
      'NIX':                ('PLU', 'REG_SAT',      'Nix'),
      'STYX':               ('PLU', 'REG_SAT',      'Styx'),

    # Asteroids
    '2002 JF56':            (None,  'OTHER',      '2002 JF56'),
    '2000 CM105':           (None,  'OTHER',      '2000 CM105'),
    'MASURSKY':             (None,  'OTHER',      'Masursky'),

    # TNO/KBOs
    'ARAWN':                (None,  'OTHER',      'Arawn'),
    'CHARIKLO':             (None,  'OTHER',      'Chariklo'),
    'CHIRON':               (None,  'OTHER',      'Chiron'), # Actually it's a CENTAUR!
    'ERIS':                 (None,  'OTHER',      'Eris'),
    'HAUMEA':               (None,  'OTHER',      'Haumea'),
    'IXION':                (None,  'OTHER',      'Ixion'),
    'MAKEMAKE':             (None,  'OTHER',      'Makemake'),
    'MANWE':                (None,  'OTHER',      'Manwe'),
    'ORCUS':                (None,  'OTHER',      'Orcus'),
    'QUAOAR':               (None,  'OTHER',      'Quaoar'),
    'SEDNA':                (None,  'OTHER',      'Sedna'),
    'VARDA':                (None,  'OTHER',      'Varda'),
    '1999 HG12':            (None,  'OTHER',      '1999 HG12'),
    '1999 HT11':            (None,  'OTHER',      '1999 HT11'),
    '1999 RT214':           (None,  'OTHER',      '1999 RT214'),
    '2000 CQ114':           (None,  'OTHER',      '2000 CQ114'),
    '2000 CM114':           (None,  'OTHER',      '2000 CM114'),
    '2000 FC8':             (None,  'OTHER',      '2000 FC8'),
    '2000 OB51':            (None,  'OTHER',      '2000 OB51'),
    '2000 PM30':            (None,  'OTHER',      '2000 PM30'),
    '2000 PN30':            (None,  'OTHER',      '2000 PN30'),
    '2000 QN251':           (None,  'OTHER',      '2000 QN251'),
    '2001 FL185':           (None,  'OTHER',      '2001 FL185'),
    '2001 KP77':            (None,  'OTHER',      '2001 KP77'),
    '2002 GZ31':            (None,  'OTHER',      '2002 GZ31'),
    '2002 MS4':             (None,  'OTHER',      '2002 MS4'),
    '2002 UX25':            (None,  'OTHER',      '2002 UX25'),
    '2002 VV130':           (None,  'OTHER',      '2002 VV130'),
    '2002 WC19':            (None,  'OTHER',      '2002 WC19'),
    '2003 TJ58':            (None,  'OTHER',      '2003 TJ58'),
    '2004 VE131':           (None,  'OTHER',      '2004 VE131'),
    '2005 EF298':           (None,  'OTHER',      '2005 EF298'),
    '2005 SE278':           (None,  'OTHER',      '2005 SE278'),
    '2005 SF278':           (None,  'OTHER',      '2005 SF278'),
    '2010 JJ124':           (None,  'OTHER',      '2010 JJ124'),
    '2011 JX31':            (None,  'OTHER',      '2011 JX31'),
    '2014 MU69':            (None,  'OTHER',      '2014 MU69'),
    '2014 PN70':            (None,  'OTHER',      '2014 PN70'),

    # Other rings
    'CHARIKLO RING':        (None,  'RING',       'Chariklo Ring'),

    # Comets
    'SHOEMAKER LEVY 9':     (None,  'OTHER',      'Shoemaker Levy 9'),

    # Nebulae and clusters
    'NECKLACE NEBULA':      (None,  'OTHER',      'Necklace Nebula'),
    'PLEIADES':             (None,  'OTHER',      'Pleiades'),
    'ORION':                (None,  'OTHER',      'Orion'),
    'M7':                   (None,  'OTHER',      'M7'),
    'SCORPIUS':             (None,  'OTHER',      'Scorpius'),
    'TAURUS':               (None,  'OTHER',      'Taurus'),
    'NGC 3532':             (None,  'OTHER',      'NGC 3532'),

    # Misc
    'FLATFIELD':            (None,  'OTHER',      'Flatfield'),
    'ACQ-ECLPSE':           (None,  'OTHER',      'Acq-Eclpse'),
    'SYSTEM':               (None,  'OTHER',      'System'),

    # Stars
    'STAR':                 (None,  'OTHER',      'Star'),
    'SUN':                  (None,  'OTHER',      'Sun'),
    '126_TAU':              (None,  'OTHER',      '126 Tau'),
    '13_LYR':               (None,  'OTHER',      '13 Lyr (R Lyr)'),
    '26_TAU':               (None,  'OTHER',      '26 Tau'),
    '28_SGR':               (None,  'OTHER',      '28 Sgr'),
    '3_CEN':                (None,  'OTHER',      '3 Cen'),
    '30_PSC':               (None,  'OTHER',      '30 Psc'),
    '56_LEO':               (None,  'OTHER',      '56 Leo'),
    'ALF_ARA':              (None,  'OTHER',      'Alp Ara'),
    'ALF_AUR':              (None,  'OTHER',      'Alp Aur (Capella)'),
    'ALF_BOO':              (None,  'OTHER',      'Alp Boo (Arcturus)'),
    'ALF_CAR':              (None,  'OTHER',      'Alp Car (Canopus)'),
    'ALF_CEN':              (None,  'OTHER',      'Alp Cen'),
    'ALF_CET':              (None,  'OTHER',      'Alp Cet'),
    'ALF_CMA':              (None,  'OTHER',      'Alp CMa (Sirius)'),
    'ALF_CMI':              (None,  'OTHER',      'Alp CMi (Procyon)'),
    'ALF_CRU':              (None,  'OTHER',      'Alp Cru'),
    'ALF01_CRU':            (None,  'OTHER',      'Alp1 Cru'),
    'ALF_ERI':              (None,  'OTHER',      'Alp Eri'),
    'ALF_HER':              (None,  'OTHER',      'Alp Her'),
    'ALF_HYA':              (None,  'OTHER',      'Alp Hya'),
    'ALF_LEO':              (None,  'OTHER',      'Alp Leo (Regulus)'),
    'ALF_LUP':              (None,  'OTHER',      'Alp Lup'),
    'ALF_LYR':              (None,  'OTHER',      'Alp Lyr (Vega)'),
    'ALF_ORI':              (None,  'OTHER',      'Alp Ori (Betelgeuse)'),
    'ALF_PAV':              (None,  'OTHER',      'Alp Pav'),
    'ALF_PSA':              (None,  'OTHER',      'Alp PsA (Fomalhaut)'),
    'ALF_SCO':              (None,  'OTHER',      'Alp Sco (Antares)'),
    'ALF_SEX':              (None,  'OTHER',      'Alp Sex'),
    'ALF_TAU':              (None,  'OTHER',      'Alp Tau (Aldebaran)'),
    'ALF_TRA':              (None,  'OTHER',      'Alp TrA'),
    'ALF_VIR':              (None,  'OTHER',      'Alp Vir (Spica)'),
    'B_CEN':                (None,  'OTHER',      'b Cen (SAO 205839)'),
    'BET_AND':              (None,  'OTHER',      'Bet And'),
    'BET_CEN':              (None,  'OTHER',      'Bet Cen'),
    'BET_CMA':              (None,  'OTHER',      'Bet CMa'),
    'BET_CRU':              (None,  'OTHER',      'Bet Cru'),
    'BET_GRU':              (None,  'OTHER',      'Bet Gru'),
    'BET_HYA':              (None,  'OTHER',      'Bet Hya'),
    'BET_LIB':              (None,  'OTHER',      'Bet Lib'),
    'BET_LUP':              (None,  'OTHER',      'Bet Lup'),
    'BET_ORI':              (None,  'OTHER',      'Bet Ori (Rigel)'),
    'BET_PEG':              (None,  'OTHER',      'Bet Peg'),
    'BET_PER':              (None,  'OTHER',      'Bet Per (Algol)'),
    'BET_PSA':              (None,  'OTHER',      'Bet PsA'),
    'BET01_SGR':            (None,  'OTHER',      'Bet1 Sgr'),
    'BET_UMI':              (None,  'OTHER',      'Bet UMi'),
    'CHI_AQR':              (None,  'OTHER',      'Chi Aqr'),
    'CHI_CEN':              (None,  'OTHER',      'Chi Cen'),
    'CHI_CYG':              (None,  'OTHER',      'Chi Cyg'),
    'DEL_AQR':              (None,  'OTHER',      'Del Aqr'),
    'DEL_CEN':              (None,  'OTHER',      'Del Cen'),
    'DEL_CET':              (None,  'OTHER',      'Del Cet'),
    'DEL_LUP':              (None,  'OTHER',      'Del Lup'),
    'DEL_OPH':              (None,  'OTHER',      'Del Oph'),
    'DEL_ORI':              (None,  'OTHER',      'Del Ori'),
    'DEL_PER':              (None,  'OTHER',      'Del Per'),
    'DEL_SCO':              (None,  'OTHER',      'Del Sco'),
    'DEL_VIR':              (None,  'OTHER',      'Del Vir'),
    'EPS_CAS':              (None,  'OTHER',      'Eps Cas'),
    'EPS_CEN':              (None,  'OTHER',      'Eps Cen'),
    'EPS_CMA':              (None,  'OTHER',      'Eps CMa'),
    'EPS_LUP':              (None,  'OTHER',      'Eps Lup'),
    'EPS_MIC':              (None,  'OTHER',      'Eps Mic'),
    'EPS_MUS':              (None,  'OTHER',      'Eps Mus'),
    'EPS_ORI':              (None,  'OTHER',      'Eps Ori'),
    'EPS_PEG':              (None,  'OTHER',      'Eps Peg'),
    'EPS_PER':              (None,  'OTHER',      'Eps Per'),
    'EPS_PSA':              (None,  'OTHER',      'Eps PsA'),
    'EPS_SGR':              (None,  'OTHER',      'Eps Sgr'),
    'ETA_CAR':              (None,  'OTHER',      'Eta Car'),
    'ETA_CMA':              (None,  'OTHER',      'Eta CMa'),
    'ETA_LUP':              (None,  'OTHER',      'Eta Lup'),
    'ETA_SGR':              (None,  'OTHER',      'Eta Sgr'),
    'ETA_UMA':              (None,  'OTHER',      'Eta UMa'),
    'G_CEN':                (None,  'OTHER',      '2 Cen'),
    'G_HER':                (None,  'OTHER',      '30 Her'),
    'GAM_AND':              (None,  'OTHER',      'Gam And'),
    'GAM_ARA':              (None,  'OTHER',      'Gam Ara'),
    'GAM_CAS':              (None,  'OTHER',      'Gam Cas'),
    'GAM_CNC':              (None,  'OTHER',      'Gam Cnc'),
    'GAM_COL':              (None,  'OTHER',      'Gam Col'),
    'GAM_CRU':              (None,  'OTHER',      'Gam Cru'),
    'GAM_ERI':              (None,  'OTHER',      'Gam Eri'),
    'GAM_GRU':              (None,  'OTHER',      'Gam Gru'),
    'GAM_LUP':              (None,  'OTHER',      'Gam Lup'),
    'GAM_ORI':              (None,  'OTHER',      'Gam Ori'),
    'GAM_PEG':              (None,  'OTHER',      'Gam Peg'),
    'HD_205905':            (None,  'OTHER',      'HD 205905'),
    'HD_339479':            (None,  'OTHER',      'HD 339479'),
    'HD_37962':             (None,  'OTHER',      'HD 37962'),
    'HD_71334':             (None,  'OTHER',      'HD 71334'),
    'IK_TAU':               (None,  'OTHER',      'NML Tau'),
    'IO_CEN':               (None,  'OTHER',      'Iot Cen'),
    'IO_HER':               (None,  'OTHER',      'Iot Her'),
    'IO_ORI':               (None,  'OTHER',      'Iot Ori'),
    'IRC_+10216':           (None,  'OTHER',      'CW Leo (IRC +10216)'),
    'KAP_CEN':              (None,  'OTHER',      'Kap Cen'),
    'KAP01_CET':            (None,  'OTHER',      'Kap1 Cet'),
    'KAP_CMA':              (None,  'OTHER',      'Kap CMa'),
    'KAP_ORI':              (None,  'OTHER',      'Kap Ori'),
    'KAP_SCO':              (None,  'OTHER',      'Kap Sco'),
    'KAP_VEL':              (None,  'OTHER',      'Kap Vel'),
    'KSI01_CET':            (None,  'OTHER',      'Xi Cet'),
    'KSI02_CET':            (None,  'OTHER',      'Xi2 Cet'),
    'L2_PUP':               (None,  'OTHER',      'L2 Pup'),
    'LAM_AQL':              (None,  'OTHER',      'Lam Aql'),
    'LAM_AQR':              (None,  'OTHER',      'Lam Aqr'),
    'LAM_CET':              (None,  'OTHER',      'Lam Cet'),
    'LAM_SCO':              (None,  'OTHER',      'Lam Sco'),
    'LAM_TAU':              (None,  'OTHER',      'Lam Tau'),
    'LAM_VEL':              (None,  'OTHER',      'Lam Vel'),
    'LMC_303':              (None,  'OTHER',      'LMC 303'),
    'MU_CEN':               (None,  'OTHER',      'Mu Cen'),
    'MU_CEP':               (None,  'OTHER',      'Mu Cep'),
    'MU_GEM':               (None,  'OTHER',      'Mu Gem'),
    'MU_PSA':               (None,  'OTHER',      'Mu PsA'),
    'MU_SCO':               (None,  'OTHER',      'Mu Sco'),
    'MU_SGR':               (None,  'OTHER',      'Mu Sgr'),
    'NU_CEN':               (None,  'OTHER',      'Nu Cen'),
    'NU_VIR':               (None,  'OTHER',      'Nu Vir'),
    'OME_VIR':              (None,  'OTHER',      'Ome Vir'),
    'OMI_CET':              (None,  'OTHER',      'Omi Cet'),
    'PI.01_GRU':            (None,  'OTHER',      'Pi1 Gru'),
    'PI.04_ORI':            (None,  'OTHER',      'Pi4 Ori'),
    'PSI_CEN':              (None,  'OTHER',      'Psi Cen'),
    'R_AQL':                (None,  'OTHER',      'R Aqu'),
    'R_AQR':                (None,  'OTHER',      'R Aqr'),
    'R_CAR':                (None,  'OTHER',      'R Car'),
    'R_CAS':                (None,  'OTHER',      'R Cas'),
    'R_DOR':                (None,  'OTHER',      'R Dor'),
    'R_HYA':                (None,  'OTHER',      'R Hya'),
    'R_LEO':                (None,  'OTHER',      'R Leo'),
    'RHO_PER':              (None,  'OTHER',      'Rho Per'),
    'RS_CNC':               (None,  'OTHER',      'RS Cnc'),
    'RW_LMI':               (None,  'OTHER',      'RW LMi'),
    'RX_LEP':               (None,  'OTHER',      'RX Lep'),
    'S_LEP':                (None,  'OTHER',      'S Lep'),
    'SIG_SGR':              (None,  'OTHER',      'Sig Sgr'),
    'T_CEP':                (None,  'OTHER',      'T Cep'),
    'TET_ARA':              (None,  'OTHER',      'The Ara'),
    'TET_CAR':              (None,  'OTHER',      'The Car'),
    'TET_HYA':              (None,  'OTHER',      'The Hya'),
    'TET02_TAU':            (None,  'OTHER',      '78 Tau'),
    'TX_CAM':               (None,  'OTHER',      'TX Cam'),
    'V_HYA':                (None,  'OTHER',      'V Hya'),
    'VX_SGR':               (None,  'OTHER',      'VX Sgr'),
    'VY_CMA':               (None,  'OTHER',      'VY CMa'),
    'W_AQL':                (None,  'OTHER',      'W Aql'),
    'W_HYA':                (None,  'OTHER',      'W Hya'),
    'X_OPH':                (None,  'OTHER',      'X Oph'),
    'ZET_CEN':              (None,  'OTHER',      'Zet Cen'),
    'ZET_CMA':              (None,  'OTHER',      'Zet CMa'),
    'ZET_OPH':              (None,  'OTHER',      'Zet Oph'),
    'ZET_ORI':              (None,  'OTHER',      'Zet Ori'),
    'ZET_PER':              (None,  'OTHER',      'Zet Per'),
    'ZET_PUP':              (None,  'OTHER',      'Zet Pup'),
}

# Map each star name to its RA and DEC
STAR_RA_DEC = {
    '126_TAU':              ( 85.323823650,  16.534145916),
    '13_LYR':               (283.833759285,  43.946092080),
    '26_TAU':               ( 57.237257777,  23.857132186),
    '28_SGR':               (281.585879011, -22.392173922),
    '3_CEN':                (207.956672333, -32.994085194),
    '30_PSC':               (  0.490063442,  -6.014074564),
    '56_LEO':               (164.006120830,   6.185368757),
    'ALF_ARA':              (262.960381368, -49.876145011),
    'ALF_AUR':              ( 79.172327958,  45.997991472),
    'ALF_BOO':              (213.915300292,  19.182409167),
    'ALF_CAR':              ( 95.987957833, -52.695661389),
    'ALF_CEN':              (219.873833042, -60.832221944),
    'ALF_CET':              ( 45.569887792,   4.089738778),
    'ALF_CMA':              (101.287155333, -16.716115861),
    'ALF_CMI':              (114.825497917,   5.224987556),
    'ALF_CRU':              (186.649563417, -63.099092861),
    'ALF01_CRU':            (186.649566667, -63.099091667),
    'ALF_ERI':              ( 24.428522833, -57.236752806),
    'ALF_HER':              (258.661909083,  14.390340611),
    'ALF_HYA':              (141.896844583,  -8.658599528),
    'ALF_LEO':              (152.092962458,  11.967208778),
    'ALF_LUP':              (220.482315778, -47.388198746),
    'ALF_LYR':              (279.234734792,  38.783688944),
    'ALF_ORI':              ( 88.792939000,   7.407064000),
    'ALF_PAV':              (306.411904375, -56.735089722),
    'ALF_PSA':              (344.412692708, -29.622237028),
    'ALF_SCO':              (247.351915417, -26.432002611),
    'ALF_SEX':              (151.984508879,  -0.371673199),
    'ALF_TAU':              ( 68.980162792,  16.509302361),
    'ALF_TRA':              (252.166229500, -69.027711833),
    'ALF_VIR':              (201.298247375, -11.161319472),
    'B_CEN':                (220.489961165, -37.793498340),
    'BET_AND':              ( 17.433016167,  35.620557639),
    'BET_CEN':              (210.955855625, -60.373035167),
    'BET_CMA':              ( 95.674938970, -17.955918709),
    'BET_CRU':              (191.930286542, -59.688772000),
    'BET_GRU':              (340.666876125, -46.884576444),
    'BET_HYA':              (178.227172875, -33.908129778),
    'BET_LIB':              (229.251724250,  -9.382914417),
    'BET_LUP':              (224.633022333, -43.133963861),
    'BET_ORI':              ( 78.634467083,  -8.201638361),
    'BET_PEG':              (345.943572750,  28.082787111),
    'BET_PER':              ( 47.042218542,  40.955646667),
    'BET_PSA':              (337.876376594, -32.346073708),
    'BET01_SGR':            (290.659578409, -44.458985404),
    'BET_UMI':              (222.676357500,  74.155503944),
    'CHI_AQR':              (349.212246505,  -7.726500629),
    'CHI_CEN':              (211.511534353, -41.179632994),
    'CHI_CYG':              (297.641351627,  32.914058245),
    'DEL_AQR':              (343.662547584, -15.820791134),
    'DEL_CEN':              (182.089573489, -50.722427393),
    'DEL_CET':              ( 39.870649125,   0.328509583),
    'DEL_LUP':              (230.343021820, -40.647506175),
    'DEL_OPH':              (243.586410542,  -3.694322556),
    'DEL_ORI':              ( 83.001667042,  -0.299095111),
    'DEL_PER':              ( 55.731267734,  47.787548509),
    'DEL_SCO':              (240.083355333, -22.621706417),
    'DEL_VIR':              (193.900869191,   3.397470340),
    'EPS_CAS':              ( 28.598859071,  63.670103394),
    'EPS_CEN':              (204.971907250, -53.466391139),
    'EPS_CMA':              (104.656453167, -28.972086167),
    'EPS_LUP':              (230.670284402, -44.689615177),
    'EPS_MIC':              (319.484516642, -32.172542089),
    'EPS_MUS':              (184.392821503, -67.960735731),
    'EPS_ORI':              ( 84.053388958,  -1.201919139),
    'EPS_PEG':              (326.046483914,   9.875008653),
    'EPS_PER':              ( 59.463466863,  40.010215317),
    'EPS_PSA':              (340.163936167, -27.043602187),
    'EPS_SGR':              (276.042993333, -34.384616472),
    'ETA_CAR':              (161.264772937, -59.684430850),
    'ETA_CMA':              (111.023759500, -29.303105500),
    'ETA_LUP':              (240.030532733, -38.396708679),
    'ETA_SGR':              (274.406812716, -36.761685201),
    'ETA_UMA':              (206.885157333,  49.313266722),
    'G_CEN':                (207.361340629, -34.450775808),
    'G_HER':                (247.160619105,  41.881677942),
    'GAM_AND':              ( 30.974801208,  42.329728417),
    'GAM_ARA':              (261.348580463, -56.377726326),
    'GAM_CAS':              ( 14.177215417,  60.716740278),
    'GAM_CNC':              (130.821450830,  21.468500220),
    'GAM_COL':              ( 89.384206570, -35.283282021),
    'GAM_CRU':              (187.791498375, -57.113213444),
    'GAM_ERI':              ( 59.507362287, -13.508519381),
    'GAM_GRU':              (328.482192484, -37.364855271),
    'GAM_LUP':              (233.785201458, -41.166756861),
    'GAM_ORI':              ( 81.282763542,   6.349703278),
    'GAM_PEG':              (  3.308963462,  15.183593544),
    'HD_205905':            (324.792296010, -27.306573896),
    'HD_339479':            (301.201186075,  26.483508059),
    'HD_37962':             ( 85.216524637, -31.351106996),
    'HD_71334':             (126.456315441, -29.930591803),
    'IK_TAU':               ( 58.370368708,  11.406073878),
    'IO_HER':               (264.866193333,  46.006331945),
    'IO_CEN':               (209.907936987, -56.148672972),
    'IO_ORI':               ( 83.601016047,  -4.411121205),
    'IRC_+10216':           (146.989193000,  13.278768000),
    'KAP_CEN':              (224.790353909, -42.104196366),
    'KAP01_CET':            ( 49.840401335,   3.370198650),
    'KAP_CMA':              (102.460247193, -32.508478467),
    'KAP_ORI':              ( 86.939120168,  -9.669604919),
    'KAP_SCO':              (265.621980000, -39.029983083),
    'KAP_VEL':              (140.528406708, -55.010667134),
    'KSI01_CET':            ( 33.249990386,   8.846722866),
    'KSI02_CET':            ( 37.039821079,   8.460060225),
    'L2_PUP':               (108.384658765, -44.639739707),
    'LAM_AQL':              (286.562248792,  -4.882564305),
    'LAM_AQR':              (343.153655135,  -7.579606384),
    'LAM_CET':              ( 44.928749465,   8.907358298),
    'LAM_SCO':              (263.402167167, -37.103823556),
    'LAM_TAU':              ( 60.170065490,  12.490340538),
    'LAM_VEL':              (136.998991125, -43.432590917),
    'LMC_303':              ( 84.694583333, -69.040277778),
    'MU_CEN':               (207.404119289, -42.473730443),
    'MU_CEP':               (325.876921073,  58.780044495),
    'MU_GEM':               ( 95.740111917,  22.513582750),
    'MU_PSA':               (332.095894906, -32.988438405),
    'MU_SCO':               (252.967666667, -38.047333333),
    'MU_SGR':               (273.440870167, -21.058831687),
    'NU_CEN':               (207.376151828, -41.687708908),
    'NU_VIR':               (176.464831557,   6.529372580),
    'OME_VIR':              (174.615030283,   8.134296206),
    'OMI_CET':              ( 34.836633750,  -2.977637667),
    'PI.01_GRU':            (335.684190458, -45.947947639),
    'PI.04_ORI':            ( 72.801519670,   5.605103418),
    'PSI_CEN':              (215.139301196, -37.885293094),
    'R_AQL':                (286.592712711,   8.230000123),
    'R_AQR':                (355.956095808, -15.284495620),
    'R_CAR':                (143.060831835, -62.788901444),
    'R_CAS':                (359.603625122,  51.388803327),
    'R_DOR':                ( 69.189963625, -62.077165944),
    'R_HYA':                (202.428257781, -23.281326300),
    'R_LEO':                (146.889516587,  11.428839801),
    'RHO_PER':              ( 46.294141042,  38.840276194),
    'RS_CNC':               (137.661657658,  30.963137767),
    'RW_LMI':               (154.009514456,  30.571938082),
    'RX_LEP':               ( 77.845298094, -11.849089503),
    'S_LEP':                ( 91.439788424, -24.195563353),
    'SIG_SGR':              (283.816360417, -26.296724111),
    'T_CEP':                (317.382430086,  68.490886151),
    'TET_ARA':              (271.657797041, -50.091475701),
    'TET_CAR':              (160.739174864, -64.394450221),
    'TET_HYA':              (138.591109977,   2.314343943),
    'TET02_TAU':            ( 67.165602280,  15.870867391),
    'TX_CAM':               ( 75.213154150,  56.181692530),
    'V_HYA':                (162.905255859, -21.250094345),
    'VX_SGR':               (272.016846450, -22.224063818),
    'VY_CMA':               (110.743036542, -25.767565417),
    'W_AQL':                (288.847325608,  -7.047307920),
    'W_HYA':                (207.258340964, -28.367647780),
    'X_OPH':                (279.588048818,   8.834110894),
    'ZET_CEN':              (208.884940208, -47.288374500),
    'ZET_CMA':              ( 95.078300166, -30.063366734),
    'ZET_OPH':              (249.289746060, -10.567091520),
    'ZET_ORI':              ( 85.189694417,  -1.942573583),
    'ZET_PER':              ( 58.533010313,  31.883633684),
    'ZET_PUP':              (120.896031417, -40.003147806),
}

# Keywords in supplemental index filenames that indicate they contain surface
# geo info in the absence of an actual surface geo summary file.
SUPPLEMENTAL_INDEX_FILES_WITH_SURFACE_GEO_INFO = [
    'CUBE_EQUI'
]

# A Dictionary that stores the desired volumes in a volset.
# {volset: pattern of desired volumes}
# If the pattern is not matched, we will skip importing that specific volume.
DESIRED_VOLUMES_IN_VOLSET = {
    # we will ignore volumes smaller than 0402 for COCIRS_0xxx
    'COCIRS_0xxx': r'(COCIRS_040[2-9]|COCIRS_041\d|COCIRS_0[5-9]\d{2})$',
}

# Note: threshold values are obtained and determined by observing the results
# from OPUS. Voyager location:
# North
# 1980-11-12T05:15:45.520
# South
# 1980-11-13T04:19:30.640
# North
# 1981-08-26T04:18:21.080
# South
# 1985-11-06T17:22:30.040
# North
# 1986-01-24T17:10:13.320
# South
THRESHOLD_START_TIME_VG_AT_NORTH = [
    '1980-11-12T05:15:45.520',
    '1980-11-13T04:19:30.640',
    '1981-08-26T04:16:45.080',
    '1985-11-06T17:22:30.040',
    '1986-01-24T17:10:13.320'
]

DSN_NAMES = {
    14: 'Goldstone 14m',
    15: 'Goldstone 34m',
    24: 'Goldstone 34m',
    25: 'Goldstone 34m',
    26: 'Goldstone 34m',
    34: 'Canberra 34m',
    35: 'Canberra 34m',
    36: 'Canberra 34m',
    43: 'Canberra 70m',
    54: 'Madrid 34m',
    55: 'Madrid 34m',
    63: 'Madrid 70m',
    65: 'Madrid 34m'
}
