################################################################################
# data_config.py
#
# These configuration parameters are specific to the data sets that are being
# imported. See also mult_config.py.
################################################################################

# param_info form types that invoke mult_ tables
GROUP_FORM_TYPES = ['GROUP', 'TARGETS']

# A list of all tables we populate, in order, for each observation index row.
# If you change something here, be sure to update do_table_names.py as well.
TABLES_TO_POPULATE = ['obs_general',
                      'obs_pds',
                      'obs_mission_<MISSION>',
                      'obs_instrument_<INST>',
                      'obs_type_image',
                      'obs_wavelength',
                      'obs_occultation',
                      'obs_files',
                      'obs_ring_geometry',
                      'obs_surface_geometry',
                      'obs_surface_geometry_name',
                      'obs_surface_geometry__<TARGET>']

# These mult tables have an extra column to allow for target_name grouping
MULT_TABLES_WITH_TARGET_GROUPING = ['mult_obs_general_target_name',
                                   'mult_obs_surface_geometry_name_target_name']

# These instruments have ring geo available (maybe)
# This is only used to give a warning if the ring geo isn't available
INSTRUMENTS_WITH_RING_GEO = ['COISS',
                             'COUVIS',
                             'COVIMS',
                             'NHLORRI',
                             'VGISS']

# These instruments have surface geo available (maybe)
# This is only used to give a warning if the surface geo isn't available
INSTRUMENTS_WITH_SURFACE_GEO = ['COISS',
                                'COUVIS',
                                'COVIMS',
                                'NHLORRI',
                                'VGISS']

# Mapping from mission abbreviation (UC) to full mission name (LC)
# These are used for table names
MISSION_ABBREV_TO_MISSION_TABLE_SFX = {
    'CO':  'cassini',
    'GB':  'earth',
    'GO':  'galileo',
    'HST': 'hubble',
    'NH':  'new_horizons',
    'VG':  'voyager'
}

# Mapping from mission abbreviation (UC) to full mission name (displayable)
MISSION_ABBREV_TO_MISSION_NAME = {
    'CO':  'Cassini',
    'GB':  'Ground-based',
    'GO':  'Galileo',
    'HST': 'Hubble',
    'NH':  'New Horizons',
    'VG':  'Voyager'
}

# Mapping from instrument host abbreviation to mission abbreviation
INST_HOST_ABBREV_TO_MISSION_ABBREV = {
    'CO':  'CO',
    'GB':  'GB',
    'GO':  'GO',
    'HST': 'HST',
    'NH':  'NH',
    'VG1': 'VG',
    'VG2': 'VG'
}

# Mapping from instrument host abbreviation to instrument host name
INST_HOST_ABBREV_TO_INST_HOST = {
    'CO':  'Cassini',
    'GB':  'Ground-based',
    'GO':  'Galileo',
    'HST': 'Hubble',
    'NH':  'New Horizons',
    'VG1': 'Voyager 1',
    'VG2': 'Voyager 2'
}

# Mapping from instrument abbreviation to mission abbreviation
INSTRUMENT_ABBREV_TO_MISSION_ABBREV = {
    'COCIRS':    'CO',
    'COISS':     'CO',
    'CORSS':     'CO',
    'COUVIS':    'CO',
    'COVIMS':    'CO',
    'GOSSI':     'GO',
    'HSTACS':    'HST',
    'HSTNICMOS': 'HST',
    'HSTSTIS':   'HST',
    'HSTWFC3':   'HST',
    'HSTWFPC2':  'HST',
    'NHLORRI':   'NH',
    'NHMVIC':    'NH',
    'VGISS':     'VG'
}

# Mapping from instrument abbrev to instrument name
INSTRUMENT_ABBREV_TO_INSTRUMENT_NAME = {
    'COCIRS':      'Cassini CIRS',
    'COISS':       'Cassini ISS',
    'COUVIS':      'Cassini UVIS',
    'COVIMS':      'Cassini VIMS',
    'GOSSI':       'Galileo SSI',
    'HSTACS':      'Hubble ACS',
    'HSTNICMOS':   'Hubble NICMOS',
    'HSTSTIS':     'Hubble STIS',
    'HSTWFC3':     'Hubble WFC3',
    'HSTWFPC2':    'Hubble WFPC2',
    'NHLORRI':     'New Horizons LORRI',
    'NHMVIC':      'New Horizons MVIC',
    'VGISS':       'Voyager ISS',
    # Ground-based
    'ESO1MAPPH':   'ESO 1-Meter Aperture Photometer',
    'ESO22MAPPH':  'ESO 2.2-Meter Aperture Photometer',
    'IRTFURAC':    'NASA IRTF URAC',
    'LICK1MCCDC':  'Lick 1-Meter CCD Camera',
    'MCD27MIIRAR': 'McDonald Observatory 2.7-Meter INSB IR Array',
    'PAL200CIRC':  'Palomar Observatory 200-Inch Cassegrain IR Camera'
}

# Mapping from VOLUME ID prefix to instrument name
VOLUME_ID_PREFIX_TO_INSTRUMENT_NAME = {
    'COCIRS': 'COCIRS',
    'COISS':  'COISS',
    'CORSS':  'CORSS',
    'COUVIS': 'COUVIS',
    'COVIMS': 'COVIMS',
    'EBROCC': None, # The instrument must be looked up in the label file
    'GO':     'GOSSI',
    'HSTI1':  'HSTWFC3',
    'HSTJ0':  'HSTACS',
    'HSTJ1':  'HSTACS',
    'HSTN0':  'HSTNICMOS',
    'HSTN1':  'HSTNICMOS',
    'HSTO0':  'HSTSTIS',
    'HSTO1':  'HSTSTIS',
    'HSTU0':  'HSTWFPC2',
    'HSTU1':  'HSTWFPC2',
    'NHJULO': 'NHLORRI',
    'NHLALO': 'NHLORRI',
    'NHPCLO': 'NHLORRI',
    'NHPELO': 'NHLORRI',
    'NHJUMV': 'NHMVIC',
    'NHLAMV': 'NHMVIC',
    'NHPCMV': 'NHMVIC',
    'NHPEMV': 'NHMVIC',
    'VGISS':  'VGISS'
}

# Mapping from VOLUME ID prefix to mission abbreviation
VOLUME_ID_PREFIX_TO_MISSION_ABBREV = {
    'COCIRS': 'CO',
    'COISS':  'CO',
    'CORSS':  'CO',
    'COUVIS': 'CO',
    'COVIMS': 'CO',
    'EBROCC': 'GB',
    'GO':     'GO',
    'HSTI1':  'HST',
    'HSTJ0':  'HST',
    'HSTJ1':  'HST',
    'HSTN0':  'HST',
    'HSTN1':  'HST',
    'HSTO0':  'HST',
    'HSTO1':  'HST',
    'HSTU0':  'HST',
    'HSTU1':  'HST',
    'NHJULO': 'NH',
    'NHLALO': 'NH',
    'NHPCLO': 'NH',
    'NHPELO': 'NH',
    'NHJUMV': 'NH',
    'NHLAMV': 'NH',
    'NHPCMV': 'NH',
    'NHPEMV': 'NH',
    'VGISS':  'VG'
}

# Mapping from VOLUME root to observation type
VOLUME_ID_ROOT_TO_TYPE = {
    'COCIRS_5xxx': 'OBS',
    'COCIRS_6xxx': 'OBS',
    'COISS_1xxx':  'OBS',
    'COISS_2xxx':  'OBS',
    'CORSS_8xxx':  'OCC',
    'COUVIS_0xxx': 'OBS',
    'COUVIS_8xxx': 'OCC',
    'COVIMS_0xxx': 'OBS',
    'COVIMS_8xxx': 'OCC',
    'EBROCC_xxxx': 'OCC',
    'GO_0xxx':     'OBS',
    'HSTIx_xxxx':  'OBS',
    'HSTJx_xxxx':  'OBS',
    'HSTNx_xxxx':  'OBS',
    'HSTOx_xxxx':  'OBS',
    'HSTUx_xxxx':  'OBS',
    'NHxxLO_xxxx': 'OBS',
    'NHxxMV_xxxx': 'OBS',
    'VGISS_5xxx':  'OBS',
    'VGISS_6xxx':  'OBS',
    'VGISS_7xxx':  'OBS',
    'VGISS_8xxx':  'OBS'
}

# Some instruments (I'm looking at you, Cassini) don't use the official IAU
# names for targets, but we want to in OPUS.
TARGET_NAME_MAPPING = {
    # These are found in COISS
    'ERRIAPO':          'ERRIAPUS',
    'HYROKKIN':         'HYRROKKIN',
    'K07S4':            'ANTHE',
    'SKADI':            'SKATHI',
    'SUTTUNG':          'SUTTUNGR',
    'THRYM':            'THRYMR',

    'S7_2004':          'S/2004 S 7',
    'S8_2004':          'FORNJOT',
    'S12_2004':         'S/2004 S 12',
    'S13_2004':         'S/2004 S 13',
    'S14_2004':         'HATI',
    'S17_2004':         'S/2004 S 17',
    'S18_2004':         'BESTLA',
    'S1_2006':          'S/2006 S 1',
    'S3_2006':          'S/2006 S 3',
    'S2_2007':          'S/2007 S 2',
    'S3_2007':          'S/2007 S 3',

    # These are found in COUVIS
    'ATLAS:':           'ATLAS',
    'AG':               'AEGAEON',
    'DA':               'DAPHNIS',
    'ME':               'METHONE',
    'PL':               'PALLENE',
    'PO':               'POLYDEUCES',
    'IPH':              'INTERSTELLAR MEDIUM', # Interstellar H/He survey

    # These are found in HST
    '174567-VARDA':     'VARDA',
    '90482ORCUS':       'ORCUS',
    '1999HG12':         '1999 HG12',
    '118378':           '1999 HT11',
    '1999-RT214':       '1999 RT214',
    '80806':            '2000 CM105',
    '60458-2000-CM114': '2000 CM114',
    '2000CQ114':        '2000 CQ114',
    '2000-CQ114':       '2000 CQ114',
    '2000-FC8':         '2000 FC8',
    '2000-OB51':        '2000 OB51',
    '2000-PM30':        '2000 PM30',
    '2000-PN30':        '2000 PN30',
    '2000QN251':        '2000 QN251',
    '2001-FL185':       '2001 FL185',
    '119070':           '2001 KP77',
    '2002VV130':        '2002 VV130',
    '119979':           '2002 WC19',
    '182933':           '2002 GZ31',
    '2002UX25':         '2002 UX25',
    '2003TJ58':         '2003 TJ58',
    '2003QW111':        'MANWE',
    '2003UB313':        'ERIS',
    '2004VE131':        '2004 VE131',
    '2005EF298':        '2005 EF298',
    '2005SE278':        '2005 SE278',
    '2005SF278':        '2005 SF278',
    '2011-JX31':        '2011 JX31',
    '2014MU69':         '2014 MU69',
    '2014PN70':         '2014 PN70',
    'KBO-G1':           '2014 PN70',
    'NECKLACE-NEBULA':  'NECKLACE NEBULA',
    'CHARIKLORING':     'CHARIKLO RING',

    # These are found in NH
    '136472 MAKEMAKE':  'MAKEMAKE',
    '136108 HAUMEA':    'HAUMEA',
    '10199 CHARIKLO':   'CHARIKLO',
    '15810 ARAWN':      'ARAWN',
    '50000 QUAOAR':     'QUAOAR',
    '28978 IXION':      'IXION',
    'ASTEROID 307261':  '2002 MS4',
    '2060 CHIRON':      'CHIRON',
    '132524 APL':       '2002 JF56',

    # Misc
    'S/2000 J 11':      'DIA',

    'CALIB':            'CALIBRATION',
    'N/A':              'NONE',
    'UNK':              'UNKNOWN',
    'UNK SAT':          'UNKNOWN',
    'NON_SCIENC':       'NONE',
    'NON SCIENC':       'NONE',
    'NON SCIENCE':      'NONE',

    # Stars
    '126 TAU':          '126_TAU',
    '126TAU':           '126_TAU',
    '205839':           'B_CEN',
    '26TAU':            '26_TAU',
    '2CEN':             'G_CEN',
    '28SGR':            '28_SGR',
    '28 SGR':           '28_SGR',
    '30HER':            'G_HER',
    '30PSC':            '30_PSC',
    '3CEN':             '3_CEN',
    '56LEO':            '56_LEO',
    '78TAU':            'TET02_TAU',
    'ALP1CRU':          'ALF01_CRU',
    'ALPARA':           'ALF_ARA',
    'ALPAUR':           'ALF_AUR',
    'ALPCEN':           'ALF_CEN',
    'ALPCET':           'ALF_CET',
    'ALPCMA':           'ALF_CMA',
    'ALPCMI':           'ALF_CMI',
    'ALPCRU':           'ALF_CRU',
    'ALPERI':           'ALF_ERI',
    'ALPHER':           'ALF_HER',
    'ALPHYA':           'ALF_HYA',
    'ALPLEO':           'ALF_LEO',
    'ALPLUP':           'ALF_LUP',
    'ALPLYR':           'ALF_LYR',
    'ALPORI':           'ALF_ORI',
    'ALPPAV':           'ALF_PAV',
    'ALPSCO':           'ALF_SCO',
    'ALPSEX':           'ALF_SEX',
    'ALPTAU':           'ALF_TAU',
    'ALPTRA':           'ALF_TRA',
    'ALPVIR':           'ALF_VIR',
    'ARCTURUS':         'ALF_BOO',
    'BETAND':           'BET_AND',
    'BETCEN':           'BET_CEN',
    'BETCMA':           'BET_CMA',
    'BETA CMA':         'BET_CMA',
    'BETCRU':           'BET_CRU',
    'BETGRU':           'BET_GRU',
    'BETHYA':           'BET_HYA',
    'BETLIB':           'BET_LIB',
    'BETLUP':           'BET_LUP',
    'BETORI':           'BET_ORI',
    'BETPEG':           'BET_PEG',
    'BETPER':           'BET_PER',
    'BETPSA':           'BET_PSA',
    'BETSGR':           'BET_SGR',
    'BETUMI':           'BET_UMI',
    'CALSTAR3':         'KAP01_CET',
    'CANOPUS':          'ALF_CAR',
    'CHIAQR':           'CHI_AQR',
    'CHICEN':           'CHI_CEN',
    'CHICYG':           'CHI_CYG',
    'CWLEO':            'IRC_+10216',
    'DELAQR':           'DEL_AQR',
    'DELCEN':           'DEL_CEN',
    'DELCET':           'DEL_CET',
    'DELLUP':           'DEL_LUP',
    'DELOPH':           'DEL_OPH',
    'DELORI':           'DEL_ORI',
    'DELPER':           'DEL_PER',
    'DELSCO':           'DEL_SCO',
    'DELVIR':           'DEL_VIR',
    'EPSCAS':           'EPS_CAS',
    'EPSCEN':           'EPS_CEN',
    'EPSCMA':           'EPS_CMA',
    'EPSLUP':           'EPS_LUP',
    'EPSMIC':           'EPS_MIC',
    'EPSMUS':           'EPS_MUS',
    'EPSORI':           'EPS_ORI',
    'EPSPEG':           'EPS_PEG',
    'EPSPER':           'EPS_PER',
    'EPSPSA':           'EPS_PSA',
    'EPSSGR':           'EPS_SGR',
    'ETACAR':           'ETA_CAR',
    'ETACMA':           'ETA_CMA',
    'ETALUP':           'ETA_LUP',
    'ETASGR':           'ETA_SGR',
    'ETAUMA':           'ETA_UMA',
    'FOMALHAUT':        'ALF_PSA',
    'GAMAND':           'GAM_AND',
    'GAMARA':           'GAM_ARA',
    'GAMCAS':           'GAM_CAS',
    'GAMCNC':           'GAM_CNC',
    'GAMCOL':           'GAM_COL',
    'GAMCRU':           'GAM_CRU',
    'GAMERI':           'GAM_ERI',
    'GAMGRU':           'GAM_GRU',
    'GAMLUP':           'GAM_LUP',
    'GAMORI':           'GAM_ORI',
    'GAMPEG':           'GAM_PEG',
    'HD 205905':        'HD_205905',
    'HD339':            'HD_339479',
    'HD 37962':         'HD_37962',
    'HD71334':          'HD_71334',
    'IOTCEN':           'IO_CEN',
    'IOTORI':           'IO_ORI',
    'KAPCEN':           'KAP_CEN',
    'KAPCMA':           'KAP_CMA',
    'KAPORI':           'KAP_ORI',
    'KAPSCO':           'KAP_SCO',
    'KAPVEL':           'KAP_VEL',
    'L2PUP':            'L2_PUP',
    'LAMAQL':           'LAM_AQL',
    'LAMAQR':           'LAM_AQR',
    'LAMCET':           'LAM_CET',
    'LAMSCO':           'LAM_SCO',
    'LAMTAU':           'LAM_TAU',
    'LAMVEL':           'LAM_VEL',
    'LMC303':           'LMC_303',
    'MUCEN':            'MU_CEN',
    'MUCEP':            'MU_CEP',
    'MUGEM':            'MU_GEM',
    'MUPSA':            'MU_PSA',
    'MUSCO':            'MU_SCO',
    'MUSGR':            'MU_SGR',
    'NMLTAURI':         'IK_TAU',
    'NUCEN':            'NU_CEN',
    'NUVIR':            'NU_VIR',
    'OMEVIR':           'OME_VIR',
    'OMICET':           'OMI_CET',
    'PI1GRU':           'PI.01_GRU',
    'PI4ORI':           'PI.04_ORI',
    'PSICEN':           'PSI_CEN',
    'RAQL':             'R_AQL',
    'RAQR':             'R_AQR',
    'RCAR':             'R_CAR',
    'RCAS':             'R_CAS',
    'RDOR':             'R_DOR',
    'RDORADUS':         'R_DOR',
    'RHOPER':           'RHO_PER',
    'RHYA':             'R_HYA',
    'RLEO':             'R_LEO',
    'RLYR':             'R_LYR',
    'RSCNC':            'RS_CNC',
    'RWLMI':            'RW_LMI',
    'RXLEP':            'RX_LEP',
    'SAO205839':        'SAO_205839',
    'SIGSGR':           'SIG_SGR',
    'SIGMA SGR':        'SIG_SGR',
    'SLEP':             'S_LEP',
    'SPICA':            'ALF_VIR',
    'TAU78':            'TET02_TAU',
    'TCEP':             'T_CEP',
    'THEARA':           'TET_ARA',
    'THECAR':           'TET_CAR',
    'THETA CAR':        'TET_CAR',
    'THEHYA':           'TET_HYA',
    'TXCAM':            'TX_CAM',
    'VEGA':             'ALF_LYR',
    'VHYA':             'V_HYA',
    'VXSGR':            'VX_SGR',
    'VYCMA':            'VY_CMA',
    'WAQL':             'W_AQL',
    'WHYA':             'W_HYA',
    'XICET':            'XI_CET',
    'XI2CET':           'XI2_CET',
    'XOPH':             'X_OPH',
    'ZETCEN':           'ZET_CEN',
    'ZETCMA':           'ZET_CMA',
    'ZETOPH':           'ZET_OPH',
    'ZETORI':           'ZET_ORI',
    'ZETPER':           'ZET_PER',
    'ZETPUP':           'ZET_PUP',
}

# Map each possible target name to:
#   1. Planet name it is associated with, or None if not associated with a
#      planet
#   2. Target class
#   3. Pretty name
# Note that if you add a new target class here, you also have to update the
# enum field and mult_options in obs_general.json
TARGET_NAME_INFO = {
    'NONE':                 (None,  'OTHER',        'None'),
    'UNKNOWN':              (None,  'OTHER',        'Unknown'),
    'OTHER':                (None,  'OTHER',        'Other'),
    'DARK':                 (None,  'CALIBRATION',  'Dark'),
    'CALIBRATION':          (None,  'CALIBRATION',  'Calibration'),
    'CAL LAMPS':            (None,  'CALIBRATION',  'Calibration Lamps'),
    'PLAQUE':               (None,  'CALIBRATION',  'Plaque'),
    'SKY':                  (None,  'SKY',          'Sky'),
    'BLACK SKY':            (None,  'SKY',          'Black Sky'),
    'DARK SKY':             (None,  'SKY',          'Dark Sky'),
    'SOLAR WIND':           (None,  'OTHER',        'Solar Wind'),
    'INTERSTELLAR MEDIUM':  (None,  'OTHER',        'Interstellar Medium'),
    'DUST':                 (None,  'OTHER',        'Dust'),

    'VENUS':                ('VEN', 'PLANET',       'Venus'),

    'EARTH':                ('EAR', 'PLANET',       'Earth'),
      'MOON':               ('EAR', 'REG_SAT',      'Moon'),

    'MARS':                 ('MAR', 'PLANET',       'Mars'),

    'JUPITER':              ('JUP', 'PLANET',       'Jupiter'),
      'ADRASTEA':           ('JUP', 'REG_SAT',      'Adrastea'),
      'AITNE':              ('JUP', 'IRR_SAT',      'Aitne'),
      'AMALTHEA':           ('JUP', 'REG_SAT',      'Amalthea'),
      'ANANKE':             ('JUP', 'IRR_SAT',      'Ananke'),
      'AOEDE':              ('JUP', 'IRR_SAT',      'Aoede'),
      'ARCHE':              ('JUP', 'IRR_SAT',      'Arche'),
      'AUTONOE':            ('JUP', 'IRR_SAT',      'Autonoe'),
      'CALLIRRHOE':         ('JUP', 'IRR_SAT',      'Callirrhoe'),
      'CALLISTO':           ('JUP', 'REG_SAT',      'Callisto'),
      'CARME':              ('JUP', 'IRR_SAT',      'Carme'),
      'CARPO':              ('JUP', 'IRR_SAT',      'Carpo'),
      'CHALDENE':           ('JUP', 'IRR_SAT',      'Chaldene'),
      'CYLLENE':            ('JUP', 'IRR_SAT',      'Cyllene'),
      'DIA':                ('JUP', 'IRR_SAT',      'Dia'),
      'ELARA':              ('JUP', 'IRR_SAT',      'Elara'),
      'ERINOME':            ('JUP', 'IRR_SAT',      'Erinome'),
      'EUANTHE':            ('JUP', 'IRR_SAT',      'Euanthe'),
      'EUKELADE':           ('JUP', 'IRR_SAT',      'Eukelade'),
      'EUPORIE':            ('JUP', 'IRR_SAT',      'Euporie'),
      'EUROPA':             ('JUP', 'REG_SAT',      'Europa'),
      'EURYDOME':           ('JUP', 'IRR_SAT',      'Eurydome'),
      'GANYMEDE':           ('JUP', 'REG_SAT',      'Ganymede'),
      'HARPALYKE':          ('JUP', 'IRR_SAT',      'Harpalyke'),
      'HEGEMONE':           ('JUP', 'IRR_SAT',      'Hegemone'),
      'HELIKE':             ('JUP', 'IRR_SAT',      'Helike'),
      'HERMIPPE':           ('JUP', 'IRR_SAT',      'Hermippe'),
      'HERSE':              ('JUP', 'IRR_SAT',      'Herse'),
      'HIMALIA':            ('JUP', 'IRR_SAT',      'Himalia'),
      'IO':                 ('JUP', 'REG_SAT',      'Io'),
      'IOCASTE':            ('JUP', 'IRR_SAT',      'Iocaste'),
      'ISONOE':             ('JUP', 'IRR_SAT',      'Isonoe'),
      'KALE':               ('JUP', 'IRR_SAT',      'Kale'),
      'KALLICHOR':          ('JUP', 'IRR_SAT',      'Kallichor'),
      'KALYKE':             ('JUP', 'IRR_SAT',      'Kalyke'),
      'KORE':               ('JUP', 'IRR_SAT',      'Kore'),
      'LEDA':               ('JUP', 'IRR_SAT',      'Leda'),
      'LYSITHEA':           ('JUP', 'IRR_SAT',      'Lysithea'),
      'MEGACLITE':          ('JUP', 'IRR_SAT',      'Megaclite'),
      'METIS':              ('JUP', 'REG_SAT',      'Metis'),
      'MNEME':              ('JUP', 'IRR_SAT',      'Mneme'),
      'ORTHOSIE':           ('JUP', 'IRR_SAT',      'Orthosie'),
      'PASIPHAE':           ('JUP', 'IRR_SAT',      'Pasiphae'),
      'PASITHEE':           ('JUP', 'IRR_SAT',      'Pasithee'),
      'PRAXIDIKE':          ('JUP', 'IRR_SAT',      'Praxidike'),
      'S/2003 J 2':         ('JUP', 'IRR_SAT',      'S/2003 J 2'),
      'S/2003 J 3':         ('JUP', 'IRR_SAT',      'S/2003 J 3'),
      'S/2003 J 4':         ('JUP', 'IRR_SAT',      'S/2003 J 4'),
      'S/2003 J 5':         ('JUP', 'IRR_SAT',      'S/2003 J 5'),
      'S/2003 J 9':         ('JUP', 'IRR_SAT',      'S/2003 J 9'),
      'S/2003 J 10':        ('JUP', 'IRR_SAT',      'S/2003 J 10'),
      'S/2003 J 12':        ('JUP', 'IRR_SAT',      'S/2003 J 12'),
      'S/2003 J 15':        ('JUP', 'IRR_SAT',      'S/2003 J 15'),
      'S/2003 J 16':        ('JUP', 'IRR_SAT',      'S/2003 J 16'),
      'S/2003 J 18':        ('JUP', 'IRR_SAT',      'S/2003 J 18'),
      'S/2003 J 19':        ('JUP', 'IRR_SAT',      'S/2003 J 19'),
      'S/2003 J 23':        ('JUP', 'IRR_SAT',      'S/2003 J 23'),
      'S/2010 J 1':         ('JUP', 'IRR_SAT',      'S/2010 J 1'),
      'S/2010 J 2':         ('JUP', 'IRR_SAT',      'S/2010 J 2'),
      'S/2011 J 1':         ('JUP', 'IRR_SAT',      'S/2011 J 1'),
      'S/2011 J 2':         ('JUP', 'IRR_SAT',      'S/2011 J 2'),
      'SINOPE':             ('JUP', 'IRR_SAT',      'Sinope'),
      'SPONDE':             ('JUP', 'IRR_SAT',      'Sponde'),
      'TAYGETE':            ('JUP', 'IRR_SAT',      'Taygete'),
      'THEBE':              ('JUP', 'REG_SAT',      'Thebe'),
      'THELXINOE':          ('JUP', 'IRR_SAT',      'Thelxinoe'),
      'THEMISTO':           ('JUP', 'IRR_SAT',      'Themisto'),
      'THYONE':             ('JUP', 'IRR_SAT',      'Thyone'),
      'J MINOR SAT':        ('JUP', 'IRR_SAT',      'Jupiter Minor Satellites'),
      'J RINGS':            ('JUP', 'RING',         'Jupiter Rings'),

    'SATURN':               ('SAT', 'PLANET',       'Saturn'),
      'AEGAEON':            ('SAT', 'REG_SAT',      'Aegaeon'),
      'AEGIR':              ('SAT', 'IRR_SAT',      'Aegir'),
      'ALBIORIX':           ('SAT', 'IRR_SAT',      'Albiorix'),
      'ANTHE':              ('SAT', 'REG_SAT',      'Anthe'),
      'ATLAS':              ('SAT', 'REG_SAT',      'Atlas'),
      'BEBHIONN':           ('SAT', 'IRR_SAT',      'Bebhionn'),
      'BERGELMIR':          ('SAT', 'IRR_SAT',      'Bergelmir'),
      'BESTLA':             ('SAT', 'IRR_SAT',      'Bestla'),
      'CALYPSO':            ('SAT', 'REG_SAT',      'Calypso'),
      'DAPHNIS':            ('SAT', 'REG_SAT',      'Daphnis'),
      'DIONE':              ('SAT', 'REG_SAT',      'Dione'),
      'ENCELADUS':          ('SAT', 'REG_SAT',      'Enceladus'),
      'EPIMETHEUS':         ('SAT', 'REG_SAT',      'Epimetheus'),
      'ERRIAPUS':           ('SAT', 'IRR_SAT',      'Erriapus'),
      'FARBAUTI':           ('SAT', 'IRR_SAT',      'Farbauti'),
      'FENRIR':             ('SAT', 'IRR_SAT',      'Fenrir'),
      'FORNJOT':            ('SAT', 'IRR_SAT',      'Fornjot'),
      'GREIP':              ('SAT', 'IRR_SAT',      'Greip'),
      'HATI':               ('SAT', 'IRR_SAT',      'Hati'),
      'HELENE':             ('SAT', 'REG_SAT',      'Helene'),
      'HYPERION':           ('SAT', 'REG_SAT',      'Hyperion'),
      'HYRROKKIN':          ('SAT', 'IRR_SAT',      'Hyrrokkin'),
      'IAPETUS':            ('SAT', 'REG_SAT',      'Iapetus'),
      'IJIRAQ':             ('SAT', 'IRR_SAT',      'Ijiraq'),
      'JANUS':              ('SAT', 'REG_SAT',      'Janus'),
      'JARNSAXA':           ('SAT', 'IRR_SAT',      'Jarnsaxa'),
      'K07S4':              ('SAT', 'IRR_SAT',      'K07s4'),
      'KARI':               ('SAT', 'IRR_SAT',      'Kari'),
      'KIVIUQ':             ('SAT', 'IRR_SAT',      'Kiviuq'),
      'LOGE':               ('SAT', 'IRR_SAT',      'Loge'),
      'METHONE':            ('SAT', 'REG_SAT',      'Methone'),
      'MIMAS':              ('SAT', 'REG_SAT',      'Mimas'),
      'MUNDILFARI':         ('SAT', 'IRR_SAT',      'Mundilfari'),
      'NARVI':              ('SAT', 'IRR_SAT',      'Narvi'),
      'PAALIAQ':            ('SAT', 'IRR_SAT',      'Paaliaq'),
      'PALLENE':            ('SAT', 'REG_SAT',      'Pallene'),
      'PANDORA':            ('SAT', 'REG_SAT',      'Pandora'),
      'PAN':                ('SAT', 'REG_SAT',      'Pan'),
      'PHOEBE':             ('SAT', 'IRR_SAT',      'Phoebe'),
      'POLYDEUCES':         ('SAT', 'REG_SAT',      'Polydeuces'),
      'PROMETHEUS':         ('SAT', 'REG_SAT',      'Prometheus'),
      'RHEA':               ('SAT', 'REG_SAT',      'Rhea'),
      'S/2004 S 12':        ('SAT', 'IRR_SAT',      'S/2004 S 12'),
      'S/2004 S 13':        ('SAT', 'IRR_SAT',      'S/2004 S 13'),
      'S/2004 S 17':        ('SAT', 'IRR_SAT',      'S/2004 S 17'),
      'S/2004 S 7':         ('SAT', 'IRR_SAT',      'S/2004 S 7'),
      'S/2006 S 1':         ('SAT', 'IRR_SAT',      'S/2006 S 1'),
      'S/2006 S 3':         ('SAT', 'IRR_SAT',      'S/2006 S 3'),
      'S/2007 S 2':         ('SAT', 'IRR_SAT',      'S/2007 S 2'),
      'S/2007 S 3':         ('SAT', 'IRR_SAT',      'S/2007 S 3'),
      'SIARNAQ':            ('SAT', 'IRR_SAT',      'Siarnaq'),
      'SKATHI':             ('SAT', 'IRR_SAT',      'Skathi'),
      'SKOLL':              ('SAT', 'IRR_SAT',      'Skoll'),
      'SURTUR':             ('SAT', 'IRR_SAT',      'Surtur'),
      'SUTTUNGR':           ('SAT', 'IRR_SAT',      'Suttungr'),
      'TARQEQ':             ('SAT', 'IRR_SAT',      'Tarqeq'),
      'TARVOS':             ('SAT', 'IRR_SAT',      'Tarvos'),
      'TELESTO':            ('SAT', 'REG_SAT',      'Telesto'),
      'TETHYS':             ('SAT', 'REG_SAT',      'Tethys'),
      'THRYMR':             ('SAT', 'IRR_SAT',      'Thrymr'),
      'TITAN':              ('SAT', 'REG_SAT',      'Titan'),
      'YMIR':               ('SAT', 'IRR_SAT',      'Ymir'),
      'S RINGS':            ('SAT', 'RING',         'Saturn Rings'),

    'URANUS':               ('URA', 'PLANET',       'Uranus'),
      'ARIEL':              ('URA', 'REG_SAT',      'Ariel'),
      'BELINDA':            ('URA', 'REG_SAT',      'Belinda'),
      'BIANCA':             ('URA', 'REG_SAT',      'Bianca'),
      'CALIBAN':            ('URA', 'IRR_SAT',      'Caliban'),
      'CORDELIA':           ('URA', 'REG_SAT',      'Cordelia'),
      'CRESSIDA':           ('URA', 'REG_SAT',      'Cressida'),
      'CUPID':              ('URA', 'REG_SAT',      'Cupid'),
      'DESDEMONA':          ('URA', 'REG_SAT',      'Desdemona'),
      'FERDINAND':          ('URA', 'IRR_SAT',      'Ferdinand'),
      'FRANCISCO':          ('URA', 'IRR_SAT',      'Francisco'),
      'JULIET':             ('URA', 'REG_SAT',      'Juliet'),
      'MAB':                ('URA', 'REG_SAT',      'Mab'),
      'MARGARET':           ('URA', 'IRR_SAT',      'Margaret'),
      'MIRANDA':            ('URA', 'REG_SAT',      'Miranda'),
      'OBERON':             ('URA', 'REG_SAT',      'Oberon'),
      'OPHELIA':            ('URA', 'REG_SAT',      'Ophelia'),
      'PERDITA':            ('URA', 'REG_SAT',      'Perdita'),
      'PORTIA':             ('URA', 'REG_SAT',      'Portia'),
      'PROSPERO':           ('URA', 'IRR_SAT',      'Prospero'),
      'PUCK':               ('URA', 'REG_SAT',      'Puck'),
      'ROSALIND':           ('URA', 'REG_SAT',      'Rosalind'),
      'SETEBOS':            ('URA', 'IRR_SAT',      'Setebos'),
      'STEPHANO':           ('URA', 'IRR_SAT',      'Stephano'),
      'SYCORAX':            ('URA', 'IRR_SAT',      'Sycorax'),
      'TITANIA':            ('URA', 'REG_SAT',      'Titania'),
      'TRINCULO':           ('URA', 'IRR_SAT',      'Trinculo'),
      'UMBRIEL':            ('URA', 'REG_SAT',      'Umbriel'),
      'U RINGS':            ('URA', 'RING',         'Uranus Rings'),

    'NEPTUNE':              ('NEP', 'PLANET',       'Neptune'),
      'CHARON':             ('NEP', 'IRR_SAT',      'Charon'),
      'DESPINA':            ('NEP', 'REG_SAT',      'Despina'),
      'GALATEA':            ('NEP', 'REG_SAT',      'Galatea'),
      'HALIMEDE':           ('NEP', 'IRR_SAT',      'Halimede'),
      'HYDRA':              ('NEP', 'IRR_SAT',      'Hydra'),
      'KERBEROS':           ('NEP', 'IRR_SAT',      'Kerberos'),
      'LAOMEDEIA':          ('NEP', 'IRR_SAT',      'Laomedeia'),
      'LARISSA':            ('NEP', 'REG_SAT',      'Larissa'),
      'NAIAD':              ('NEP', 'REG_SAT',      'Naiad'),
      'NEREID':             ('NEP', 'IRR_SAT',      'Nereid'),
      'NESO':               ('NEP', 'IRR_SAT',      'Neso'),
      'NIX':                ('NEP', 'IRR_SAT',      'Nix'),
      'PLUTO':              ('NEP', 'IRR_SAT',      'Pluto'),
      'PROTEUS':            ('NEP', 'REG_SAT',      'Proteus'),
      'PSAMATHE':           ('NEP', 'IRR_SAT',      'Psamathe'),
      'SAO':                ('NEP', 'IRR_SAT',      'Sao'),
      'STYX':               ('NEP', 'IRR_SAT',      'Styx'),
      'THALASSA':           ('NEP', 'REG_SAT',      'Thalassa'),
      'TRITON':             ('NEP', 'IRR_SAT',      'Triton'),
      'N RINGS':            ('NEP', 'RING',         'Neptune Rings'),

    'PLUTO':                ('PLU', 'PLANET',       'Pluto'),
      'CHARON':             ('PLU', 'REG_SAT',      'Charon'),
      'HYDRA':              ('PLU', 'REG_SAT',      'Hydra'),
      'KERBEROS':           ('PLU', 'REG_SAT',      'Kerberos'),
      'NIX':                ('PLU', 'REG_SAT',      'Nix'),
      'STYX':               ('PLU', 'REG_SAT',      'Styx'),

    # Asteroids
    '2002 JF56':            (None,  'OTHER',      '2002 JF56'),
    '2000 CM105':           (None,  'OTHER',      '2000 CM105'),
    'MASURSKY':             (None,  'OTHER',      'Masursky'),

    # TNO/KBOs
    'ARAWN':                (None,  'OTHER',      'Arawn'),
    'CHARIKLO':             (None,  'OTHER',      'Chariklo'),
    'CHIRON':               (None,  'OTHER',      'Chiron'), # Actually it's a CENTAUR!
    'ERIS':                 (None,  'OTHER',      'Eris'),
    'HAUMEA':               (None,  'OTHER',      'Haumea'),
    'IXION':                (None,  'OTHER',      'Ixion'),
    'MAKEMAKE':             (None,  'OTHER',      'Makemake'),
    'MANWE':                (None,  'OTHER',      'Manwe'),
    'ORCUS':                (None,  'OTHER',      'Orcus'),
    'QUAOAR':               (None,  'OTHER',      'Quaoar'),
    'SEDNA':                (None,  'OTHER',      'Sedna'),
    'VARDA':                (None,  'OTHER',      'Varda'),
    '1999 HG12':            (None,  'OTHER',      '1999 HG12'),
    '1999 HT11':            (None,  'OTHER',      '1999 HT11'),
    '1999 RT214':           (None,  'OTHER',      '1999 RT214'),
    '2000 CQ114':           (None,  'OTHER',      '2000 CQ114'),
    '2000 CM114':           (None,  'OTHER',      '2000 CM114'),
    '2000 FC8':             (None,  'OTHER',      '2000 FC8'),
    '2000 OB51':            (None,  'OTHER',      '2000 OB51'),
    '2000 PM30':            (None,  'OTHER',      '2000 PM30'),
    '2000 PN30':            (None,  'OTHER',      '2000 PN30'),
    '2000 QN251':           (None,  'OTHER',      '2000 QN251'),
    '2001 FL185':           (None,  'OTHER',      '2001 FL185'),
    '2001 KP77':            (None,  'OTHER',      '2001 KP77'),
    '2002 GZ31':            (None,  'OTHER',      '2002 GZ31'),
    '2002 MS4':             (None,  'OTHER',      '2002 MS4'),
    '2002 UX25':            (None,  'OTHER',      '2002 UX25'),
    '2002 VV130':           (None,  'OTHER',      '2002 VV130'),
    '2002 WC19':            (None,  'OTHER',      '2002 WC19'),
    '2003 TJ58':            (None,  'OTHER',      '2003 TJ58'),
    '2004 VE131':           (None,  'OTHER',      '2004 VE131'),
    '2005 EF298':           (None,  'OTHER',      '2005 EF298'),
    '2005 SE278':           (None,  'OTHER',      '2005 SE278'),
    '2005 SF278':           (None,  'OTHER',      '2005 SF278'),
    '2010 JJ124':           (None,  'OTHER',      '2010 JJ124'),
    '2011 JX31':            (None,  'OTHER',      '2011 JX31'),
    '2014 MU69':            (None,  'OTHER',      '2014 MU69'),
    '2014 PN70':            (None,  'OTHER',      '2014 PN70'),

    # Other rings
    'CHARIKLO RING':        (None,  'RING',       'Chariklo RING'),

    # Comets
    'SHOEMAKER LEVY 9':     (None,  'OTHER',      'Shoemaker Levy 9'),

    # Nebulae and clusters
    'NECKLACE NEBULA':      (None,  'OTHER',      'Necklace Nebula'),
    'PLEIADES':             (None,  'OTHER',      'Pleiades'),
    'ORION':                (None,  'OTHER',      'Orion'),
    'M7':                   (None,  'OTHER',      'M7'),
    'SCORPIUS':             (None,  'OTHER',      'Scorpius'),
    'TAURUS':               (None,  'OTHER',      'Taurus'),
    'NGC 3532':             (None,  'OTHER',      'NGC 3532'),

    # Misc
    'FLATFIELD':            (None,  'OTHER',      'Flatfield'),
    'ACQ-ECLPSE':           (None,  'OTHER',      'Acq-Eclpse'),
    'SYSTEM':               (None,  'OTHER',      'System'),

    # Stars
    'STAR':                 (None,  'OTHER',      'Star'),
    'SUN':                  (None,  'OTHER',      'Sun'),
    '126_TAU':              (None,  'OTHER',      '126 Tau'),
    '28_SGR':               (None,  'OTHER',      '28 Sgr'),
    'HD_37962':             (None,  'OTHER',      'HD 37962'),
    'HD_205905':            (None,  'OTHER',      'HD 205905'),
    'B_CEN':                (None,  'OTHER',      'SAO 205839'),
    '26_TAU':               (None,  'OTHER',      '26 Tau'),
    'G_CEN':                (None,  'OTHER',      '2 Cen'),
    'G_HER':                (None,  'OTHER',      '30 Her'),
    '30_PSC':               (None,  'OTHER',      '30 Psc'),
    '3_CEN':                (None,  'OTHER',      '3 Cen'),
    '56_LEO':               (None,  'OTHER',      '56 Leo'),
    'TET02_TAU':            (None,  'OTHER',      '78 Tau'),
    'ALF01_CRU':            (None,  'OTHER',      'Alp1 Cru'),
    'ALF_ARA':              (None,  'OTHER',      'Alp Ara'),
    'ALF_AUR':              (None,  'OTHER',      'Alp Aur (Capella)'),
    'ALF_CEN':              (None,  'OTHER',      'Alp Cen'),
    'ALF_CET':              (None,  'OTHER',      'Alp Cet'),
    'ALF_CMA':              (None,  'OTHER',      'Alp CMa (Sirius)'),
    'ALF_CMI':              (None,  'OTHER',      'Alp CMi (Procyon)'),
    'ALF_CRU':              (None,  'OTHER',      'Alp Cru'),
    'ALF_ERI':              (None,  'OTHER',      'Alp Eri'),
    'ALF_HER':              (None,  'OTHER',      'Alp Her'),
    'ALF_HYA':              (None,  'OTHER',      'Alp Hya'),
    'ALF_LEO':              (None,  'OTHER',      'Alp Leo (Regulus)'),
    'ALF_LUP':              (None,  'OTHER',      'Alp Lup'),
    'ALF_LYR':              (None,  'OTHER',      'Alp Lyr'),
    'ALF_ORI':              (None,  'OTHER',      'Alp Ori (Betelgeuse)'),
    'ALF_PAV':              (None,  'OTHER',      'Alp Pav'),
    'ALF_SCO':              (None,  'OTHER',      'Alp Sco (Antares)'),
    'ALF_SEX':              (None,  'OTHER',      'Alp Sex'),
    'ALF_TAU':              (None,  'OTHER',      'Alp Tau (Aldebaran)'),
    'ALF_TRA':              (None,  'OTHER',      'Alp TrA'),
    'ALF_VIR':              (None,  'OTHER',      'Alp Vir'),
    'ALF_BOO':              (None,  'OTHER',      'Alp Boo (Arcturus)'),
    'BET_AND':              (None,  'OTHER',      'Bet And'),
    'BET_CEN':              (None,  'OTHER',      'Bet Cen'),
    'BET_CMA':              (None,  'OTHER',      'Bet CMa'),
    'BET_CRU':              (None,  'OTHER',      'Bet Cru'),
    'BET_GRU':              (None,  'OTHER',      'Bet Gru'),
    'BET_HYA':              (None,  'OTHER',      'Bet Hya'),
    'BET_LIB':              (None,  'OTHER',      'Bet Lib'),
    'BET_LUP':              (None,  'OTHER',      'Bet Lup'),
    'BET_ORI':              (None,  'OTHER',      'Bet Ori (Rigel)'),
    'BET_PEG':              (None,  'OTHER',      'Bet Peg'),
    'BET_PER':              (None,  'OTHER',      'Bet Per (Algol)'),
    'BET_PSA':              (None,  'OTHER',      'Bet PsA'),
    'BET_SGR':              (None,  'OTHER',      'Bet Sgr'),
    'BET_UMI':              (None,  'OTHER',      'Bet UMi'),
    'KAP01_CET':            (None,  'OTHER',      'Kap1 Cet'),
    'ALF_CAR':              (None,  'OTHER',      'Alp Car (Canopus)'),
    'CHI_AQR':              (None,  'OTHER',      'Chi Aqr'),
    'CHI_CEN':              (None,  'OTHER',      'Chi Cen'),
    'CHI_CYG':              (None,  'OTHER',      'Chi Cyg'),
    'IRC_+10216':           (None,  'OTHER',      'CW Leo'),
    'DEL_AQR':              (None,  'OTHER',      'Del Aqr'),
    'DEL_CEN':              (None,  'OTHER',      'Del Cen'),
    'DEL_CET':              (None,  'OTHER',      'Del Cet'),
    'DEL_LUP':              (None,  'OTHER',      'Del Lup'),
    'DEL_OPH':              (None,  'OTHER',      'Del Oph'),
    'DEL_ORI':              (None,  'OTHER',      'Del Ori'),
    'DEL_PER':              (None,  'OTHER',      'Del Per'),
    'DEL_SCO':              (None,  'OTHER',      'Del Sco'),
    'DEL_VIR':              (None,  'OTHER',      'Del Vir'),
    'EPS_CAS':              (None,  'OTHER',      'Eps Cas'),
    'EPS_CEN':              (None,  'OTHER',      'Eps Cen'),
    'EPS_CMA':              (None,  'OTHER',      'Eps CMa'),
    'EPS_LUP':              (None,  'OTHER',      'Eps Lup'),
    'EPS_MIC':              (None,  'OTHER',      'Eps Mic'),
    'EPS_MUS':              (None,  'OTHER',      'Eps Mus'),
    'EPS_ORI':              (None,  'OTHER',      'Eps Ori'),
    'EPS_PEG':              (None,  'OTHER',      'Eps Peg'),
    'EPS_PER':              (None,  'OTHER',      'Eps Per'),
    'EPS_PSA':              (None,  'OTHER',      'Eps PsA'),
    'EPS_SGR':              (None,  'OTHER',      'Eps Sgr'),
    'ETA_CAR':              (None,  'OTHER',      'Eta Car'),
    'ETA_CMA':              (None,  'OTHER',      'Eta CMa'),
    'ETA_LUP':              (None,  'OTHER',      'Eta Lup'),
    'ETA_SGR':              (None,  'OTHER',      'Eta Sgr'),
    'ETA_UMA':              (None,  'OTHER',      'Eta UMa'),
    'ALF_PSA':              (None,  'OTHER',      'Alp PsA (Fomalhaut)'),
    'GAM_AND':              (None,  'OTHER',      'Gam And'),
    'GAM_ARA':              (None,  'OTHER',      'Gam Ara'),
    'GAM_CAS':              (None,  'OTHER',      'Gam Cas'),
    'GAM_CNC':              (None,  'OTHER',      'Gam Cnc'),
    'GAM_COL':              (None,  'OTHER',      'Gam Col'),
    'GAM_CRU':              (None,  'OTHER',      'Gam Cru'),
    'GAM_ERI':              (None,  'OTHER',      'Gam Eri'),
    'GAM_GRU':              (None,  'OTHER',      'Gam Gru'),
    'GAM_LUP':              (None,  'OTHER',      'Gam Lup'),
    'GAM_ORI':              (None,  'OTHER',      'Gam Ori'),
    'GAM_PEG':              (None,  'OTHER',      'Gam Peg'),
    'HD_339479':            (None,  'OTHER',      'HD 339479'),
    'HD_71334':             (None,  'OTHER',      'HD 71334'),
    'IO_CEN':               (None,  'OTHER',      'Iot Cen'),
    'IO_ORI':               (None,  'OTHER',      'Iot Ori'),
    'KAP_CEN':              (None,  'OTHER',      'Kap Cen'),
    'KAP_CMA':              (None,  'OTHER',      'Kap CMa'),
    'KAP_ORI':              (None,  'OTHER',      'Kap Ori'),
    'KAP_SCO':              (None,  'OTHER',      'Kap Sco'),
    'KAP_VEL':              (None,  'OTHER',      'Kap Vel'),
    'LAM_AQL':              (None,  'OTHER',      'Lam Aql'),
    'LAM_AQR':              (None,  'OTHER',      'Lam Aqr'),
    'LAM_CET':              (None,  'OTHER',      'Lam Cet'),
    'LAM_SCO':              (None,  'OTHER',      'Lam Sco'),
    'LAM_TAU':              (None,  'OTHER',      'Lam Tau'),
    'LAM_VEL':              (None,  'OTHER',      'Lam Vel'),
    'LMC_303':              (None,  'OTHER',      'LMC 303'),
    'MU_CEN':               (None,  'OTHER',      'Mu Cen'),
    'MU_CEP':               (None,  'OTHER',      'Mu Cep'),
    'MU_GEM':               (None,  'OTHER',      'Mu Gem'),
    'MU_PSA':               (None,  'OTHER',      'Mu PsA'),
    'MU_SCO':               (None,  'OTHER',      'Mu Sco'),
    'MU_SGR':               (None,  'OTHER',      'Mu Sgr'),
    'IK_TAU':               (None,  'OTHER',      'NML Tau'),
    'L2_PUP':               (None,  'OTHER',      'L2 Pup'),
    'NU_CEN':               (None,  'OTHER',      'Nu Cen'),
    'NU_VIR':               (None,  'OTHER',      'Nu Vir'),
    'OME_VIR':              (None,  'OTHER',      'Ome Vir'),
    'OMI_CET':              (None,  'OTHER',      'Omi Cet'),
    'PI.01_GRU':            (None,  'OTHER',      'Pi1 Gru'),
    'PI.04_ORI':            (None,  'OTHER',      'Pi4 Ori'),
    'PSI_CEN':              (None,  'OTHER',      'Psi Cen'),
    'R_AQL':                (None,  'OTHER',      'R Aqu'),
    'R_AQR':                (None,  'OTHER',      'R Aqr'),
    'R_CAR':                (None,  'OTHER',      'R Car'),
    'R_CAS':                (None,  'OTHER',      'R Cas'),
    'R_DOR':                (None,  'OTHER',      'R Dor'),
    'RHO_PER':              (None,  'OTHER',      'Rho Per'),
    'R_HYA':                (None,  'OTHER',      'R Hya'),
    'R_LEO':                (None,  'OTHER',      'R Leo'),
    'R_LYR':                (None,  'OTHER',      'R Lyr'),
    'RS_CNC':               (None,  'OTHER',      'RS Cnc'),
    'RW_LMI':               (None,  'OTHER',      'RW LMi'),
    'RX_LEP':               (None,  'OTHER',      'RX Lep'),
    'SAO_205839':           (None,  'OTHER',      'SAO 205839'),
    'SIG_SGR':              (None,  'OTHER',      'Sig Sgr'),
    'S_LEP':                (None,  'OTHER',      'S Lep'),
    'ALF_VIR':              (None,  'OTHER',      'Alp Vir (Spica)'),
    'TET02_TAU':            (None,  'OTHER',      '78 Tau'),
    'T_CEP':                (None,  'OTHER',      'T Cep'),
    'TET_ARA':              (None,  'OTHER',      'The Ara'),
    'TET_CAR':              (None,  'OTHER',      'The Car'),
    'TET_HYA':              (None,  'OTHER',      'The Hya'),
    'TX_CAM':               (None,  'OTHER',      'TX Cam'),
    'ALF_LYR':              (None,  'OTHER',      'Alp Lyr (Vega)'),
    'V_HYA':                (None,  'OTHER',      'V Hya'),
    'VX_SGR':               (None,  'OTHER',      'VX Sgr'),
    'VY_CMA':               (None,  'OTHER',      'VY CMa'),
    'W_AQL':                (None,  'OTHER',      'W Aql'),
    'W_HYA':                (None,  'OTHER',      'W Hya'),
    'XI_CET':               (None,  'OTHER',      'Xi Cet'),
    'XI2_CET':              (None,  'OTHER',      'Xi2 Cet'),
    'X_OPH':                (None,  'OTHER',      'X Oph'),
    'ZET_CEN':              (None,  'OTHER',      'Zet Cen'),
    'ZET_CMA':              (None,  'OTHER',      'Zet CMa'),
    'ZET_OPH':              (None,  'OTHER',      'Zet Oph'),
    'ZET_ORI':              (None,  'OTHER',      'Zet Ori'),
    'ZET_PER':              (None,  'OTHER',      'Zet Per'),
    'ZET_PUP':              (None,  'OTHER',      'Zet Pup'),
}

# Map each star name to its RA and DEC
STAR_RA_DEC = {
    '28_SGR': (18/24.+46/60.+20.61/3600., -(22+23/60.+31.83/3600.))
}
