"""Every target OPUS knows: its planet, its class, and the name shown for it.

A TARGET_NAME in a PDS label that this table does not describe is reported as an error
and the observation is imported without a target, which is why adding an instrument
usually means adding entries here.
`opus_import.config_targets.target_name_mapping` folds an instrument's own spelling onto
one of these names first.

A target class added here has to be added to the enum field and the ``mult_options`` in
``obs_general.json`` as well, or the import will reject the value it stores.
"""

from __future__ import annotations

# Map each possible target name to:
#   1. Planet name it is associated with, or None if not associated with a
#      planet
#   2. Target class
#   3. Pretty name
# Note that if you add a new target class here, you also have to update the
# enum field and mult_options in obs_general.json
TARGET_NAME_INFO: dict[str, tuple[str | None, str, str]] = {
    'NONE':                 (None,  'OTHER',        'None'),
    'UNKNOWN':              (None,  'OTHER',        'Unknown'),
    'OTHER':                (None,  'OTHER',        'Other'),
    'DARK':                 (None,  'CALIBRATION',  'Dark'),
    'CALIBRATION':          (None,  'CALIBRATION',  'Calibration'),
    'CAL LAMPS':            (None,  'CALIBRATION',  'Calibration Lamps'),
    'PLAQUE':               (None,  'CALIBRATION',  'Plaque'),
    'SKY':                  (None,  'SKY',          'Sky'),
    'BLACK SKY':            (None,  'SKY',          'Black Sky'),
    'DARK SKY':             (None,  'SKY',          'Dark Sky'),
    'SOLAR WIND':           (None,  'OTHER',        'Solar Wind'),
    'INTERSTELLAR MEDIUM':  (None,  'OTHER',        'Interstellar Medium'),
    'DUST':                 (None,  'OTHER',        'Dust'),

    'VENUS':                ('VEN', 'PLANET',       'Venus'),

    'EARTH':                ('EAR', 'PLANET',       'Earth'),
      'MOON':               ('EAR', 'REG_SAT',      'Moon'),

    'MARS':                 ('MAR', 'PLANET',       'Mars'),

    'JUPITER':              ('JUP', 'PLANET',       'Jupiter'),
      'ADRASTEA':           ('JUP', 'REG_SAT',      'Adrastea'),
      'AITNE':              ('JUP', 'IRR_SAT',      'Aitne'),
      'AMALTHEA':           ('JUP', 'REG_SAT',      'Amalthea'),
      'ANANKE':             ('JUP', 'IRR_SAT',      'Ananke'),
      'AOEDE':              ('JUP', 'IRR_SAT',      'Aoede'),
      'ARCHE':              ('JUP', 'IRR_SAT',      'Arche'),
      'AUTONOE':            ('JUP', 'IRR_SAT',      'Autonoe'),
      'CALLIRRHOE':         ('JUP', 'IRR_SAT',      'Callirrhoe'),
      'CALLISTO':           ('JUP', 'REG_SAT',      'Callisto'),
      'CARME':              ('JUP', 'IRR_SAT',      'Carme'),
      'CARPO':              ('JUP', 'IRR_SAT',      'Carpo'),
      'CHALDENE':           ('JUP', 'IRR_SAT',      'Chaldene'),
      'CYLLENE':            ('JUP', 'IRR_SAT',      'Cyllene'),
      'DIA':                ('JUP', 'IRR_SAT',      'Dia'),
      'ELARA':              ('JUP', 'IRR_SAT',      'Elara'),
      'ERINOME':            ('JUP', 'IRR_SAT',      'Erinome'),
      'EUANTHE':            ('JUP', 'IRR_SAT',      'Euanthe'),
      'EUKELADE':           ('JUP', 'IRR_SAT',      'Eukelade'),
      'EUPORIE':            ('JUP', 'IRR_SAT',      'Euporie'),
      'EUROPA':             ('JUP', 'REG_SAT',      'Europa'),
      'EURYDOME':           ('JUP', 'IRR_SAT',      'Eurydome'),
      'GANYMEDE':           ('JUP', 'REG_SAT',      'Ganymede'),
      'HARPALYKE':          ('JUP', 'IRR_SAT',      'Harpalyke'),
      'HEGEMONE':           ('JUP', 'IRR_SAT',      'Hegemone'),
      'HELIKE':             ('JUP', 'IRR_SAT',      'Helike'),
      'HERMIPPE':           ('JUP', 'IRR_SAT',      'Hermippe'),
      'HERSE':              ('JUP', 'IRR_SAT',      'Herse'),
      'HIMALIA':            ('JUP', 'IRR_SAT',      'Himalia'),
      'IO':                 ('JUP', 'REG_SAT',      'Io'),
      'IOCASTE':            ('JUP', 'IRR_SAT',      'Iocaste'),
      'ISONOE':             ('JUP', 'IRR_SAT',      'Isonoe'),
      'KALE':               ('JUP', 'IRR_SAT',      'Kale'),
      'KALLICHOR':          ('JUP', 'IRR_SAT',      'Kallichor'),
      'KALYKE':             ('JUP', 'IRR_SAT',      'Kalyke'),
      'KORE':               ('JUP', 'IRR_SAT',      'Kore'),
      'LEDA':               ('JUP', 'IRR_SAT',      'Leda'),
      'LYSITHEA':           ('JUP', 'IRR_SAT',      'Lysithea'),
      'MEGACLITE':          ('JUP', 'IRR_SAT',      'Megaclite'),
      'METIS':              ('JUP', 'REG_SAT',      'Metis'),
      'MNEME':              ('JUP', 'IRR_SAT',      'Mneme'),
      'ORTHOSIE':           ('JUP', 'IRR_SAT',      'Orthosie'),
      'PASIPHAE':           ('JUP', 'IRR_SAT',      'Pasiphae'),
      'PASITHEE':           ('JUP', 'IRR_SAT',      'Pasithee'),
      'PRAXIDIKE':          ('JUP', 'IRR_SAT',      'Praxidike'),
      'S/2003 J 2':         ('JUP', 'IRR_SAT',      'S/2003 J 2'),
      'S/2003 J 3':         ('JUP', 'IRR_SAT',      'S/2003 J 3'),
      'S/2003 J 4':         ('JUP', 'IRR_SAT',      'S/2003 J 4'),
      'S/2003 J 5':         ('JUP', 'IRR_SAT',      'S/2003 J 5'),
      'S/2003 J 9':         ('JUP', 'IRR_SAT',      'S/2003 J 9'),
      'S/2003 J 10':        ('JUP', 'IRR_SAT',      'S/2003 J 10'),
      'S/2003 J 12':        ('JUP', 'IRR_SAT',      'S/2003 J 12'),
      'S/2003 J 15':        ('JUP', 'IRR_SAT',      'S/2003 J 15'),
      'S/2003 J 16':        ('JUP', 'IRR_SAT',      'S/2003 J 16'),
      'S/2003 J 18':        ('JUP', 'IRR_SAT',      'S/2003 J 18'),
      'S/2003 J 19':        ('JUP', 'IRR_SAT',      'S/2003 J 19'),
      'S/2003 J 23':        ('JUP', 'IRR_SAT',      'S/2003 J 23'),
      'S/2010 J 1':         ('JUP', 'IRR_SAT',      'S/2010 J 1'),
      'S/2010 J 2':         ('JUP', 'IRR_SAT',      'S/2010 J 2'),
      'S/2011 J 1':         ('JUP', 'IRR_SAT',      'S/2011 J 1'),
      'S/2011 J 2':         ('JUP', 'IRR_SAT',      'S/2011 J 2'),
      'SINOPE':             ('JUP', 'IRR_SAT',      'Sinope'),
      'SPONDE':             ('JUP', 'IRR_SAT',      'Sponde'),
      'TAYGETE':            ('JUP', 'IRR_SAT',      'Taygete'),
      'THEBE':              ('JUP', 'REG_SAT',      'Thebe'),
      'THELXINOE':          ('JUP', 'IRR_SAT',      'Thelxinoe'),
      'THEMISTO':           ('JUP', 'IRR_SAT',      'Themisto'),
      'THYONE':             ('JUP', 'IRR_SAT',      'Thyone'),
      'J MINOR SAT':        ('JUP', 'IRR_SAT',      'Jupiter Minor Satellites'),
      'J RINGS':            ('JUP', 'RING',         'Jupiter Rings'),

    'SATURN':               ('SAT', 'PLANET',       'Saturn'),
      'AEGAEON':            ('SAT', 'REG_SAT',      'Aegaeon'),
      'AEGIR':              ('SAT', 'IRR_SAT',      'Aegir'),
      'ALBIORIX':           ('SAT', 'IRR_SAT',      'Albiorix'),
      'ANTHE':              ('SAT', 'REG_SAT',      'Anthe'),
      'ATLAS':              ('SAT', 'REG_SAT',      'Atlas'),
      'BEBHIONN':           ('SAT', 'IRR_SAT',      'Bebhionn'),
      'BERGELMIR':          ('SAT', 'IRR_SAT',      'Bergelmir'),
      'BESTLA':             ('SAT', 'IRR_SAT',      'Bestla'),
      'CALYPSO':            ('SAT', 'REG_SAT',      'Calypso'),
      'DAPHNIS':            ('SAT', 'REG_SAT',      'Daphnis'),
      'DIONE':              ('SAT', 'REG_SAT',      'Dione'),
      'ENCELADUS':          ('SAT', 'REG_SAT',      'Enceladus'),
      'EPIMETHEUS':         ('SAT', 'REG_SAT',      'Epimetheus'),
      'ERRIAPUS':           ('SAT', 'IRR_SAT',      'Erriapus'),
      'FARBAUTI':           ('SAT', 'IRR_SAT',      'Farbauti'),
      'FENRIR':             ('SAT', 'IRR_SAT',      'Fenrir'),
      'FORNJOT':            ('SAT', 'IRR_SAT',      'Fornjot'),
      'GREIP':              ('SAT', 'IRR_SAT',      'Greip'),
      'HATI':               ('SAT', 'IRR_SAT',      'Hati'),
      'HELENE':             ('SAT', 'REG_SAT',      'Helene'),
      'HYPERION':           ('SAT', 'REG_SAT',      'Hyperion'),
      'HYRROKKIN':          ('SAT', 'IRR_SAT',      'Hyrrokkin'),
      'IAPETUS':            ('SAT', 'REG_SAT',      'Iapetus'),
      'IJIRAQ':             ('SAT', 'IRR_SAT',      'Ijiraq'),
      'JANUS':              ('SAT', 'REG_SAT',      'Janus'),
      'JARNSAXA':           ('SAT', 'IRR_SAT',      'Jarnsaxa'),
      'K07S4':              ('SAT', 'IRR_SAT',      'K07s4'),
      'KARI':               ('SAT', 'IRR_SAT',      'Kari'),
      'KIVIUQ':             ('SAT', 'IRR_SAT',      'Kiviuq'),
      'LOGE':               ('SAT', 'IRR_SAT',      'Loge'),
      'METHONE':            ('SAT', 'REG_SAT',      'Methone'),
      'MIMAS':              ('SAT', 'REG_SAT',      'Mimas'),
      'MUNDILFARI':         ('SAT', 'IRR_SAT',      'Mundilfari'),
      'NARVI':              ('SAT', 'IRR_SAT',      'Narvi'),
      'PAALIAQ':            ('SAT', 'IRR_SAT',      'Paaliaq'),
      'PALLENE':            ('SAT', 'REG_SAT',      'Pallene'),
      'PANDORA':            ('SAT', 'REG_SAT',      'Pandora'),
      'PAN':                ('SAT', 'REG_SAT',      'Pan'),
      'PHOEBE':             ('SAT', 'IRR_SAT',      'Phoebe'),
      'POLYDEUCES':         ('SAT', 'REG_SAT',      'Polydeuces'),
      'PROMETHEUS':         ('SAT', 'REG_SAT',      'Prometheus'),
      'RHEA':               ('SAT', 'REG_SAT',      'Rhea'),
      'S/2004 S 12':        ('SAT', 'IRR_SAT',      'S/2004 S 12'),
      'S/2004 S 13':        ('SAT', 'IRR_SAT',      'S/2004 S 13'),
      'S/2004 S 17':        ('SAT', 'IRR_SAT',      'S/2004 S 17'),
      'S/2004 S 7':         ('SAT', 'IRR_SAT',      'S/2004 S 7'),
      'S/2006 S 1':         ('SAT', 'IRR_SAT',      'S/2006 S 1'),
      'S/2006 S 3':         ('SAT', 'IRR_SAT',      'S/2006 S 3'),
      'S/2007 S 2':         ('SAT', 'IRR_SAT',      'S/2007 S 2'),
      'S/2007 S 3':         ('SAT', 'IRR_SAT',      'S/2007 S 3'),
      'SIARNAQ':            ('SAT', 'IRR_SAT',      'Siarnaq'),
      'SKATHI':             ('SAT', 'IRR_SAT',      'Skathi'),
      'SKOLL':              ('SAT', 'IRR_SAT',      'Skoll'),
      'SURTUR':             ('SAT', 'IRR_SAT',      'Surtur'),
      'SUTTUNGR':           ('SAT', 'IRR_SAT',      'Suttungr'),
      'TARQEQ':             ('SAT', 'IRR_SAT',      'Tarqeq'),
      'TARVOS':             ('SAT', 'IRR_SAT',      'Tarvos'),
      'TELESTO':            ('SAT', 'REG_SAT',      'Telesto'),
      'TETHYS':             ('SAT', 'REG_SAT',      'Tethys'),
      'THRYMR':             ('SAT', 'IRR_SAT',      'Thrymr'),
      'TITAN':              ('SAT', 'REG_SAT',      'Titan'),
      'YMIR':               ('SAT', 'IRR_SAT',      'Ymir'),
      'S RINGS':            ('SAT', 'RING',         'Saturn Rings'),

    'URANUS':               ('URA', 'PLANET',       'Uranus'),
      'ARIEL':              ('URA', 'REG_SAT',      'Ariel'),
      'BELINDA':            ('URA', 'REG_SAT',      'Belinda'),
      'BIANCA':             ('URA', 'REG_SAT',      'Bianca'),
      'CALIBAN':            ('URA', 'IRR_SAT',      'Caliban'),
      'CORDELIA':           ('URA', 'REG_SAT',      'Cordelia'),
      'CRESSIDA':           ('URA', 'REG_SAT',      'Cressida'),
      'CUPID':              ('URA', 'REG_SAT',      'Cupid'),
      'DESDEMONA':          ('URA', 'REG_SAT',      'Desdemona'),
      'FERDINAND':          ('URA', 'IRR_SAT',      'Ferdinand'),
      'FRANCISCO':          ('URA', 'IRR_SAT',      'Francisco'),
      'JULIET':             ('URA', 'REG_SAT',      'Juliet'),
      'MAB':                ('URA', 'REG_SAT',      'Mab'),
      'MARGARET':           ('URA', 'IRR_SAT',      'Margaret'),
      'MIRANDA':            ('URA', 'REG_SAT',      'Miranda'),
      'OBERON':             ('URA', 'REG_SAT',      'Oberon'),
      'OPHELIA':            ('URA', 'REG_SAT',      'Ophelia'),
      'PERDITA':            ('URA', 'REG_SAT',      'Perdita'),
      'PORTIA':             ('URA', 'REG_SAT',      'Portia'),
      'PROSPERO':           ('URA', 'IRR_SAT',      'Prospero'),
      'PUCK':               ('URA', 'REG_SAT',      'Puck'),
      'ROSALIND':           ('URA', 'REG_SAT',      'Rosalind'),
      'SETEBOS':            ('URA', 'IRR_SAT',      'Setebos'),
      'STEPHANO':           ('URA', 'IRR_SAT',      'Stephano'),
      'SYCORAX':            ('URA', 'IRR_SAT',      'Sycorax'),
      'TITANIA':            ('URA', 'REG_SAT',      'Titania'),
      'TRINCULO':           ('URA', 'IRR_SAT',      'Trinculo'),
      'UMBRIEL':            ('URA', 'REG_SAT',      'Umbriel'),
      'U RINGS':            ('URA', 'RING',         'Uranus Rings'),

    'NEPTUNE':              ('NEP', 'PLANET',       'Neptune'),
      'DESPINA':            ('NEP', 'REG_SAT',      'Despina'),
      'GALATEA':            ('NEP', 'REG_SAT',      'Galatea'),
      'HALIMEDE':           ('NEP', 'IRR_SAT',      'Halimede'),
      'LAOMEDEIA':          ('NEP', 'IRR_SAT',      'Laomedeia'),
      'LARISSA':            ('NEP', 'REG_SAT',      'Larissa'),
      'NAIAD':              ('NEP', 'REG_SAT',      'Naiad'),
      'NEREID':             ('NEP', 'IRR_SAT',      'Nereid'),
      'NESO':               ('NEP', 'IRR_SAT',      'Neso'),
      'PROTEUS':            ('NEP', 'REG_SAT',      'Proteus'),
      'PSAMATHE':           ('NEP', 'IRR_SAT',      'Psamathe'),
      'SAO':                ('NEP', 'IRR_SAT',      'Sao'),
      'THALASSA':           ('NEP', 'REG_SAT',      'Thalassa'),
      'TRITON':             ('NEP', 'IRR_SAT',      'Triton'),
      'N RINGS':            ('NEP', 'RING',         'Neptune Rings'),

    'PLUTO':                ('PLU', 'PLANET',       'Pluto'),
      'CHARON':             ('PLU', 'REG_SAT',      'Charon'),
      'HYDRA':              ('PLU', 'REG_SAT',      'Hydra'),
      'KERBEROS':           ('PLU', 'REG_SAT',      'Kerberos'),
      'NIX':                ('PLU', 'REG_SAT',      'Nix'),
      'STYX':               ('PLU', 'REG_SAT',      'Styx'),

    # Asteroids
    '2000 CM105':           (None,  'OTHER',      '2000 CM105'),
    '2002 JF56':            (None,  'OTHER',      '2002 JF56'),
    '2002 KX14':            (None,  'OTHER',      '2002 KX14'),
    '2002 HZ84':            (None,  'OTHER',      '2002 HZ84'),
    '2004 LW31':            (None,  'OTHER',      '2004 LW31'),
    '2018 MF13':            (None,  'OTHER',      '2018 MF13'),
    '2011 HF103':           (None,  'OTHER',      '2011 HF103'),
    '2011 HJ103':           (None,  'OTHER',      '2011 HJ103'),
    '2011 HK103':           (None,  'OTHER',      '2011 HK103'),
    '2011 HZ102':           (None,  'OTHER',      '2011 HZ102'),
    '2012 HE85':            (None,  'OTHER',      '2012 HE85'),
    '2014 OE394':           (None,  'OTHER',      '2014 OE394'),
    '2014 OJ394':           (None,  'OTHER',      '2014 OJ394'),
    '2014 OS393':           (None,  'OTHER',      '2014 OS393'),
    'GASPRA':               (None,  'OTHER',      'Gaspra'),
    'IDA':                  (None,  'OTHER',      'Ida'),
    'MASURSKY':             (None,  'OTHER',      'Masursky'),

    # TNO/KBOs
    'ARAWN':                (None,  'OTHER',      'Arawn'),
    'ARROKOTH':             (None,  'OTHER',      'Arrokoth'),
    'CHARIKLO':             (None,  'OTHER',      'Chariklo'),
    'CHIRON':               (None,  'OTHER',      'Chiron'), # Actually it's a CENTAUR!
    'ERIS':                 (None,  'OTHER',      'Eris'),
    'HAUMEA':               (None,  'OTHER',      'Haumea'),
    'HUYA':                 (None,  'OTHER',      'Huya'),
    'IXION':                (None,  'OTHER',      'Ixion'),
    'MAKEMAKE':             (None,  'OTHER',      'Makemake'),
    'MANWE':                (None,  'OTHER',      'Manwe'),
    'ORCUS':                (None,  'OTHER',      'Orcus'),
    'PHOLUS':               (None,  'OTHER',      'Pholus'),
    'QUAOAR':               (None,  'OTHER',      'Quaoar'),
    'SEDNA':                (None,  'OTHER',      'Sedna'),
    'VARDA':                (None,  'OTHER',      'Varda'),
    '1999 HG12':            (None,  'OTHER',      '1999 HG12'),
    '1999 HT11':            (None,  'OTHER',      '1999 HT11'),
    '1999 RT214':           (None,  'OTHER',      '1999 RT214'),
    '2000 CQ114':           (None,  'OTHER',      '2000 CQ114'),
    '2000 CM114':           (None,  'OTHER',      '2000 CM114'),
    '2000 FC8':             (None,  'OTHER',      '2000 FC8'),
    '2000 OB51':            (None,  'OTHER',      '2000 OB51'),
    '2000 PM30':            (None,  'OTHER',      '2000 PM30'),
    '2000 PN30':            (None,  'OTHER',      '2000 PN30'),
    '2000 QN251':           (None,  'OTHER',      '2000 QN251'),
    '2001 FL185':           (None,  'OTHER',      '2001 FL185'),
    '2001 KP77':            (None,  'OTHER',      '2001 KP77'),
    '2002 GZ31':            (None,  'OTHER',      '2002 GZ31'),
    '2002 MS4':             (None,  'OTHER',      '2002 MS4'),
    '2002 UX25':            (None,  'OTHER',      '2002 UX25'),
    '2002 VV130':           (None,  'OTHER',      '2002 VV130'),
    '2002 WC19':            (None,  'OTHER',      '2002 WC19'),
    '2003 TJ58':            (None,  'OTHER',      '2003 TJ58'),
    '2004 VE131':           (None,  'OTHER',      '2004 VE131'),
    '2005 EF298':           (None,  'OTHER',      '2005 EF298'),
    '2005 SE278':           (None,  'OTHER',      '2005 SE278'),
    '2005 SF278':           (None,  'OTHER',      '2005 SF278'),
    '2010 JJ124':           (None,  'OTHER',      '2010 JJ124'),
    '2011 JW31':            (None,  'OTHER',      '2011 JW31'),
    '2011 JX31':            (None,  'OTHER',      '2011 JX31'),
    '2011 JY31':            (None,  'OTHER',      '2011 JY31'),
    '2011 JA32':            (None,  'OTHER',      '2011 JA32'),
    '2014 MU69':            (None,  'OTHER',      '2014 MU69'),
    '2014 PN70':            (None,  'OTHER',      '2014 PN70'),
    '2018 MG13':            (None,  'OTHER',      '2018 MG13'),
    '2020 KH42':            (None,  'OTHER',      '2020 KH42'),
    '2020 KO11':            (None,  'OTHER',      '2020 KO11'),
    '2020 KP11':            (None,  'OTHER',      '2020 KP11'),
    '2020 KR11':            (None,  'OTHER',      '2020 KR11'),
    '2020 KT11':            (None,  'OTHER',      '2020 KT11'),

    # Other rings
    'CHARIKLO RING':        (None,  'RING',       'Chariklo Ring'),

    # Comets
    'SHOEMAKER LEVY 9':     (None,  'OTHER',      'Shoemaker Levy 9'),

    # Nebulae and clusters
    'NECKLACE NEBULA':      (None,  'OTHER',      'Necklace Nebula'),
    'PLEIADES':             (None,  'OTHER',      'Pleiades'),
    'ORION':                (None,  'OTHER',      'Orion'),
    'M7':                   (None,  'OTHER',      'M7'),
    'SCORPIUS':             (None,  'OTHER',      'Scorpius'),
    'TAURUS':               (None,  'OTHER',      'Taurus'),
    'NGC 3532':             (None,  'OTHER',      'NGC 3532'),

    # Misc
    'FLATFIELD':            (None,  'OTHER',      'Flatfield'),
    'ACQ-ECLPSE':           (None,  'OTHER',      'Acq-Eclpse'),
    'SYSTEM':               (None,  'OTHER',      'System'),
    'VOYAGER 1':            (None,  'OTHER',      'Voyager 1'),

    # Stars
    'STAR':                 (None,  'OTHER',      'Star'),
    'SUN':                  (None,  'OTHER',      'Sun'),
    '126_TAU':              (None,  'OTHER',      '126 Tau'),
    '13_LYR':               (None,  'OTHER',      '13 Lyr (R Lyr)'),
    '26_TAU':               (None,  'OTHER',      '26 Tau'),
    '28_SGR':               (None,  'OTHER',      '28 Sgr'),
    '3_CEN':                (None,  'OTHER',      '3 Cen'),
    '30_PSC':               (None,  'OTHER',      '30 Psc'),
    '56_LEO':               (None,  'OTHER',      '56 Leo'),
    'ALF_ARA':              (None,  'OTHER',      'Alp Ara'),
    'ALF_AUR':              (None,  'OTHER',      'Alp Aur (Capella)'),
    'ALF_BOO':              (None,  'OTHER',      'Alp Boo (Arcturus)'),
    'ALF_CAR':              (None,  'OTHER',      'Alp Car (Canopus)'),
    'ALF_CEN':              (None,  'OTHER',      'Alp Cen'),
    'ALF_CET':              (None,  'OTHER',      'Alp Cet'),
    'ALF_CMA':              (None,  'OTHER',      'Alp CMa (Sirius)'),
    'ALF_CMI':              (None,  'OTHER',      'Alp CMi (Procyon)'),
    'ALF_CRU':              (None,  'OTHER',      'Alp Cru'),
    'ALF01_CRU':            (None,  'OTHER',      'Alp1 Cru'),
    'ALF_ERI':              (None,  'OTHER',      'Alp Eri'),
    'ALF_HER':              (None,  'OTHER',      'Alp Her'),
    'ALF_HYA':              (None,  'OTHER',      'Alp Hya'),
    'ALF_LEO':              (None,  'OTHER',      'Alp Leo (Regulus)'),
    'ALF_LUP':              (None,  'OTHER',      'Alp Lup'),
    'ALF_LYR':              (None,  'OTHER',      'Alp Lyr (Vega)'),
    'ALF_ORI':              (None,  'OTHER',      'Alp Ori (Betelgeuse)'),
    'ALF_PAV':              (None,  'OTHER',      'Alp Pav'),
    'ALF_PSA':              (None,  'OTHER',      'Alp PsA (Fomalhaut)'),
    'ALF_SCO':              (None,  'OTHER',      'Alp Sco (Antares)'),
    'ALF_SEX':              (None,  'OTHER',      'Alp Sex'),
    'ALF_TAU':              (None,  'OTHER',      'Alp Tau (Aldebaran)'),
    'ALF_TRA':              (None,  'OTHER',      'Alp TrA'),
    'ALF_VIR':              (None,  'OTHER',      'Alp Vir (Spica)'),
    'B_CEN':                (None,  'OTHER',      'b Cen (SAO 205839)'),
    'BET_AND':              (None,  'OTHER',      'Bet And'),
    'BET_ARI':              (None,  'OTHER',      'Bet Ari'),
    'BET_CEN':              (None,  'OTHER',      'Bet Cen'),
    'BET_CMA':              (None,  'OTHER',      'Bet CMa'),
    'BET_CRU':              (None,  'OTHER',      'Bet Cru'),
    'BET_GRU':              (None,  'OTHER',      'Bet Gru'),
    'BET_HYA':              (None,  'OTHER',      'Bet Hya'),
    'BET_LIB':              (None,  'OTHER',      'Bet Lib'),
    'BET_LUP':              (None,  'OTHER',      'Bet Lup'),
    'BET_ORI':              (None,  'OTHER',      'Bet Ori (Rigel)'),
    'BET_PEG':              (None,  'OTHER',      'Bet Peg'),
    'BET_PER':              (None,  'OTHER',      'Bet Per (Algol)'),
    'BET_PSA':              (None,  'OTHER',      'Bet PsA'),
    'BET01_SGR':            (None,  'OTHER',      'Bet1 Sgr'),
    'BET_UMI':              (None,  'OTHER',      'Bet UMi'),
    'CHI_AQR':              (None,  'OTHER',      'Chi Aqr'),
    'CHI_CEN':              (None,  'OTHER',      'Chi Cen'),
    'CHI_CYG':              (None,  'OTHER',      'Chi Cyg'),
    'CN_LEO':               (None,  'OTHER',      'CN Leo'),
    'DEL_AQR':              (None,  'OTHER',      'Del Aqr'),
    'DEL_CEN':              (None,  'OTHER',      'Del Cen'),
    'DEL_CET':              (None,  'OTHER',      'Del Cet'),
    'DEL_LUP':              (None,  'OTHER',      'Del Lup'),
    'DEL_OPH':              (None,  'OTHER',      'Del Oph'),
    'DEL_ORI':              (None,  'OTHER',      'Del Ori'),
    'DEL_PER':              (None,  'OTHER',      'Del Per'),
    'DEL_PSC':              (None,  'OTHER',      'Del Psc'),
    'DEL_SCO':              (None,  'OTHER',      'Del Sco'),
    'DEL_VIR':              (None,  'OTHER',      'Del Vir'),
    'EPS_CAS':              (None,  'OTHER',      'Eps Cas'),
    'EPS_CEN':              (None,  'OTHER',      'Eps Cen'),
    'EPS_CMA':              (None,  'OTHER',      'Eps CMa'),
    'EPS_LUP':              (None,  'OTHER',      'Eps Lup'),
    'EPS_MIC':              (None,  'OTHER',      'Eps Mic'),
    'EPS_MUS':              (None,  'OTHER',      'Eps Mus'),
    'EPS_ORI':              (None,  'OTHER',      'Eps Ori'),
    'EPS_PEG':              (None,  'OTHER',      'Eps Peg'),
    'EPS_PER':              (None,  'OTHER',      'Eps Per'),
    'EPS_PSA':              (None,  'OTHER',      'Eps PsA'),
    'EPS_SGR':              (None,  'OTHER',      'Eps Sgr'),
    'ETA_CAR':              (None,  'OTHER',      'Eta Car'),
    'ETA_CMA':              (None,  'OTHER',      'Eta CMa'),
    'ETA_LUP':              (None,  'OTHER',      'Eta Lup'),
    'ETA_SGR':              (None,  'OTHER',      'Eta Sgr'),
    'ETA_UMA':              (None,  'OTHER',      'Eta UMa'),
    'G_CEN':                (None,  'OTHER',      '2 Cen'),
    'G_HER':                (None,  'OTHER',      '30 Her'),
    'GAM_AND':              (None,  'OTHER',      'Gam And'),
    'GAM_ARA':              (None,  'OTHER',      'Gam Ara'),
    'GAM_CAS':              (None,  'OTHER',      'Gam Cas'),
    'GAM_CNC':              (None,  'OTHER',      'Gam Cnc'),
    'GAM_COL':              (None,  'OTHER',      'Gam Col'),
    'GAM_CRU':              (None,  'OTHER',      'Gam Cru'),
    'GAM_ERI':              (None,  'OTHER',      'Gam Eri'),
    'GAM_GRU':              (None,  'OTHER',      'Gam Gru'),
    'GAM_LUP':              (None,  'OTHER',      'Gam Lup'),
    'GAM_ORI':              (None,  'OTHER',      'Gam Ori'),
    'GAM_PEG':              (None,  'OTHER',      'Gam Peg'),
    'HD_205905':            (None,  'OTHER',      'HD 205905'),
    'HD_339479':            (None,  'OTHER',      'HD 339479'),
    'HD_37962':             (None,  'OTHER',      'HD 37962'),
    'HD_71334':             (None,  'OTHER',      'HD 71334'),
    'HD_151288':            (None,  'OTHER',      'HD 151288'),
    'IK_TAU':               (None,  'OTHER',      'NML Tau'),
    'IO_CEN':               (None,  'OTHER',      'Iot Cen'),
    'IO_HER':               (None,  'OTHER',      'Iot Her'),
    'IO_ORI':               (None,  'OTHER',      'Iot Ori'),
    'IRC_+10216':           (None,  'OTHER',      'CW Leo (IRC +10216)'),
    'KAP_CEN':              (None,  'OTHER',      'Kap Cen'),
    'KAP01_CET':            (None,  'OTHER',      'Kap1 Cet'),
    'KAP_CMA':              (None,  'OTHER',      'Kap CMa'),
    'KAP_ORI':              (None,  'OTHER',      'Kap Ori'),
    'KAP_SCO':              (None,  'OTHER',      'Kap Sco'),
    'KAP_VEL':              (None,  'OTHER',      'Kap Vel'),
    'KSI01_CET':            (None,  'OTHER',      'Xi Cet'),
    'KSI02_CET':            (None,  'OTHER',      'Xi2 Cet'),
    'L2_PUP':               (None,  'OTHER',      'L2 Pup'),
    'LAM_AQL':              (None,  'OTHER',      'Lam Aql'),
    'LAM_AQR':              (None,  'OTHER',      'Lam Aqr'),
    'LAM_CET':              (None,  'OTHER',      'Lam Cet'),
    'LAM_SCO':              (None,  'OTHER',      'Lam Sco'),
    'LAM_TAU':              (None,  'OTHER',      'Lam Tau'),
    'LAM_VEL':              (None,  'OTHER',      'Lam Vel'),
    'LMC_303':              (None,  'OTHER',      'LMC 303'),
    'MU_CEN':               (None,  'OTHER',      'Mu Cen'),
    'MU_CEP':               (None,  'OTHER',      'Mu Cep'),
    'MU_GEM':               (None,  'OTHER',      'Mu Gem'),
    'MU_PSA':               (None,  'OTHER',      'Mu PsA'),
    'MU_SCO':               (None,  'OTHER',      'Mu Sco'),
    'MU_SGR':               (None,  'OTHER',      'Mu Sgr'),
    'NU_CEN':               (None,  'OTHER',      'Nu Cen'),
    'NU_VIR':               (None,  'OTHER',      'Nu Vir'),
    'OME_VIR':              (None,  'OTHER',      'Ome Vir'),
    'OMI_CET':              (None,  'OTHER',      'Omi Cet'),
    'PI.01_GRU':            (None,  'OTHER',      'Pi1 Gru'),
    'PI.04_ORI':            (None,  'OTHER',      'Pi4 Ori'),
    'PSI_CEN':              (None,  'OTHER',      'Psi Cen'),
    'R_AQL':                (None,  'OTHER',      'R Aqu'),
    'R_AQR':                (None,  'OTHER',      'R Aqr'),
    'R_CAR':                (None,  'OTHER',      'R Car'),
    'R_CAS':                (None,  'OTHER',      'R Cas'),
    'R_DOR':                (None,  'OTHER',      'R Dor'),
    'R_HYA':                (None,  'OTHER',      'R Hya'),
    'R_LEO':                (None,  'OTHER',      'R Leo'),
    'RHO_PER':              (None,  'OTHER',      'Rho Per'),
    'RS_CNC':               (None,  'OTHER',      'RS Cnc'),
    'RW_LMI':               (None,  'OTHER',      'RW LMi'),
    'RX_LEP':               (None,  'OTHER',      'RX Lep'),
    'S_LEP':                (None,  'OTHER',      'S Lep'),
    'SIG_SGR':              (None,  'OTHER',      'Sig Sgr'),
    'T_CEP':                (None,  'OTHER',      'T Cep'),
    'TAU_CET':              (None,  'OTHER',      'Tau Cet'),
    'TET_ARA':              (None,  'OTHER',      'The Ara'),
    'TET_CAR':              (None,  'OTHER',      'The Car'),
    'TET_HYA':              (None,  'OTHER',      'The Hya'),
    'TET02_TAU':            (None,  'OTHER',      '78 Tau'),
    'TX_CAM':               (None,  'OTHER',      'TX Cam'),
    'V_HYA':                (None,  'OTHER',      'V Hya'),
    'VX_SGR':               (None,  'OTHER',      'VX Sgr'),
    'VY_CMA':               (None,  'OTHER',      'VY CMa'),
    'W_AQL':                (None,  'OTHER',      'W Aql'),
    'W_HYA':                (None,  'OTHER',      'W Hya'),
    'X_OPH':                (None,  'OTHER',      'X Oph'),
    'ZET_CEN':              (None,  'OTHER',      'Zet Cen'),
    'ZET_CMA':              (None,  'OTHER',      'Zet CMa'),
    'ZET_OPH':              (None,  'OTHER',      'Zet Oph'),
    'ZET_ORI':              (None,  'OTHER',      'Zet Ori'),
    'ZET_PER':              (None,  'OTHER',      'Zet Per'),
    'ZET_PUP':              (None,  'OTHER',      'Zet Pup'),
    'VARIABLE STARS IN MILKY WAY BULGE':  # NHKELO
                            (None,  'OTHER',      'Variable Stars in Milky Way Bulge'),
}
