name: Run Lint
run-name: "Run Lint: ${{ github.ref_type }} ${{ github.ref_name }} by ${{ github.triggering_actor }}"

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: "55 10 * * *"  # 2:55am PST, 3:55am PDT

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Run flake8
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
          ./run_flake8.sh
